// Английский источник строк — как у tweb (`tweb/src/lang.ts`): ключ символический,
// значение — английский текст. Ключи, совпавшие с оригиналом дословно, взяты у оригинала
// вместе с его текстом; остальные названы по его правилам (`Раздел.Подраздел.Смысл`).
// Значение-объект — форма числа (`langPackStringPluralized`), выбор формы появится в задаче 3.
//
// Файл ещё никем не используется: карту старых ключей на новые даёт `i18n/legacyKeyMap.ts`,
// подключение — отдельными задачами волны.
const lang = {
  'AccountSettings.Notifications': 'Notifications and Sounds',
  'AccountSettings.SpeakersAndCamera': 'Speakers and Camera',
  Add: 'Add',
  AddContact: 'Add to contacts',
  AddFactCheck: 'Add Fact Check',
  AddOneMemberAlertTitle: 'Add member',
  AddToFavorites: 'Add to Favorites',
  Administrators: 'Administrators',
  AllReactions: 'All reactions',
  Animations: 'Animations',
  ApproveNewMembers: 'Request Admin Approval',
  Archive: 'Archive',
  'Archive.Empty': 'No archived chats',
  ArchivedChats: 'Archived Chats',
  AreYouSureClearDrafts: 'Are you sure you want to delete all cloud drafts?',
  AreYouSureClearDraftsTitle: 'Delete cloud drafts',
  AreYouSureDeleteFewMessages: 'Are you sure you want to delete these messages?',
  AreYouSureDeleteSingleMessage: 'Are you sure you want to delete this message?',
  AreYouSureSessionTitle: 'Terminate session',
  AreYouSureSessions: 'Are you sure you want to terminate all other sessions?',
  AreYouSureSessionsTitle: 'Terminate sessions',
  AskAQuestion: 'Ask a Question',
  AttachAlbum: 'Album',
  AttachAudio: 'Voice message',
  AttachContact: 'Contact',
  AttachGif: 'GIF',
  AttachLiveLocation: 'Live Location',
  AttachLocation: 'Location',
  AttachPhoto: 'Photo',
  AttachRound: 'Video message',
  AttachSticker: 'Sticker',
  AttachVideo: 'Video',
  AuthorHiddenShort: 'Anonymous',
  AutoDeleteMessages: 'Auto-delete messages',
  'AutoDeleteMessages.SectionCaption': 'If enabled, all new messages in chats you start will be automatically deleted for everyone at some point after they have been sent. This will not affect your existing chats.',
  'AutoDeleteMessages.SectionTitle': 'Self-destruct timer',
  'AutoDeleteMessages.SetOtherTime': 'Set other time',
  AutoDeleteMessagesShort: 'Auto-delete',
  AutoDownloadAudioInfo: 'Voice messages are tiny, so they\'re always downloaded automatically.',
  AutoDownloadFilesTitle: 'Auto-download files and music',
  AutoDownloadLargeFilesInfo: 'Larger files are never downloaded automatically.',
  AutoDownloadMaxFileSize: 'Maximum file size',
  AutoDownloadMaxVideoSize: 'Max video size',
  AutoDownloadMedia: 'Auto-Download Media',
  AutoDownloadMobile: 'When using mobile data',
  AutoDownloadOnAllChats: 'On in all chats',
  AutoDownloadOnFor: 'On for %1$s',
  AutoDownloadOnUpToFor: 'Up to %1$s for %2$s',
  AutoDownloadPhotos: 'Photos',
  AutoDownloadPhotosTitle: 'Auto-download photos',
  AutoDownloadPm: 'PM',
  AutoDownloadRoaming: 'When roaming',
  // Разделители перечисления — их берёт `join()` (`lib/langPack.ts`, порт tweb :687).
  // Взяты у оригинала дословно (tweb `lang.ts:3394-3395`) вместе с именами: в оригинале
  // они тоже названы по разделу автозагрузки, откуда пришли первым потребителем.
  'AutoDownloadSettings.Delimeter': ', ',
  'AutoDownloadSettings.LastDelimeter': ' and ',
  AutoDownloadUpToOnAllChats: 'Up to %1$s in all chats',
  AutoDownloadVideos: 'Videos',
  AutoDownloadVideosTitle: 'Auto-download videos and GIFs',
  AutoDownloadWifi: 'When connected to Wi-Fi',
  AutodownloadGroupChats: 'Group Chats',
  AutodownloadPrivateChats: 'Private Chats',
  AutodownloadSizeLimitUpTo: 'up to %1$s',
  AutomaticMediaDownload: 'Automatic media download',
  AvailableReactions: 'Available reactions',
  'Bio.Description': 'Any details such as age, occupation or city.\nExample: 23 y.o. designer from San Francisco',
  BioCopied: 'Bio copied to clipboard.',
  Birthday: 'Birthday',
  'Birthday.PrivacyHint': 'In settings you can choose who will see your birthday.',
  'BlockModal.Search.Placeholder': 'Block user...',
  BlockUser: 'Block user',
  BlockedEmpty: 'None',
  BlockedEmptyDescription: 'You haven\'t blocked anyone.',
  BlockedUsers: 'Blocked Users',
  BlockedUsersInfo: 'Blocked users can\'t send you messages or add you to groups. They will not see your profile photos, stories, online and last seen status.',
  BlockedUsersInfoShort: 'Blocked users can\'t send you messages or see your profile.',
  'Boost.AlreadyBoosting': 'You are boosting this channel.',
  'Boost.Boosted': 'You boosted this channel',
  'Boost.Error.NoSlot': 'Could not boost. You need Telegram Premium and a free boost slot.',
  'Boost.Subtitle': 'Help boost this channel to unlock new features.',
  BoostChannel: 'Boost Channel',
  BoostingGiveaway: 'Giveaway',
  BoostingGiveawayEnd: 'Giveaway ended',
  BoostingGiveawayPrizes: '**Giveaway Prizes**',
  BoostingStartGiveawayConfirmTitle: 'Start Giveaway',
  BoostingWinnersDate: '**Winners Selection Date**',
  BoostsLevel2: 'Level',
  'BoostsViaGifts.Duration': 'Duration of premium subscriptions',
  'BoostsViaGifts.End': 'Date when giveaway ends',
  'BoostsViaGifts.Quantity': 'Quantity of prizes',
  Bot: 'bot',
  BotStart: 'START',
  BuyStars: 'Buy Stars',
  'Calendar.ClearHistory': 'Clear History',
  'Calendar.Next': 'Next',
  'Calendar.Previous': 'Previous',
  Call: 'Call',
  'Call.Accept': 'Accept',
  'Call.CameraOff': 'Turn off camera',
  'Call.CameraOn': 'Turn on camera',
  'Call.Decline': 'Decline',
  'Call.EncryptionKey': 'Encryption key',
  'Call.EncryptionKeyHint': 'If the emoji match on both devices, this call is end-to-end verified.',
  'Call.Input': 'Input',
  'Call.MicrophoneOff': 'Microphone is off',
  'Call.Mute': 'Mute',
  'Call.Output': 'Output',
  'Call.PrivacyError': 'This user doesn\'t accept calls',
  'Call.ShareScreen': 'Share screen',
  'Call.StatusBusy': 'Busy',
  'Call.StatusConnecting': 'Connecting...',
  'Call.StatusDeclined': 'Declined',
  'Call.StatusEnded': 'Call Ended',
  'Call.StatusNoAnswer': 'No answer',
  'Call.StatusRinging': 'Ringing...',
  'Call.StopScreenSharing': 'Stop screen sharing',
  'Call.VideoToggle': 'video',
  CallMessageCancelled: 'Cancelled call',
  CallMessageIncoming: 'Incoming Call',
  CallMessageOutgoing: 'Outgoing Call',
  CallMessageVideoIncoming: 'Incoming Video Call',
  CallMessageVideoOutgoing: 'Outgoing Video Call',
  'CallSettings.AcceptCalls': 'Accept calls on this device',
  'CallSettings.AcceptCalls.Caption': 'Turn off to stop receiving incoming calls and group video chats on this device.',
  'CallSettings.AcceptCallsShort': 'Accept Calls',
  'CallSettings.Camera': 'Device',
  'CallSettings.CameraSection': 'Camera',
  'CallSettings.DeviceDefault': 'Default',
  'CallSettings.EndCall': 'End Call',
  'CallSettings.InputDevice': 'Input device',
  'CallSettings.Microphone': 'Microphone',
  'CallSettings.OutputDevice': 'Output device',
  'CallSettings.Speakers': 'Speakers',
  'Calls.Empty': 'No recent calls',
  Cancel: 'Cancel',
  Channel: 'Channel',
  'Channel.Admin.Dismiss': 'Dismiss Admin',
  'Channel.DescriptionHolderDescrpiton': 'You can provide an optional description for your channel.',
  'Channel.DescriptionPrefix': 'You can provide an optional description for your',
  'Channel.UsernameAboutChannel': 'People can share this link with others and can find your channel using Telegram search.',
  'Channel.UsernameAboutGroup': 'People can share this link with others and find your group using Telegram search.',
  ChannelAddAdmin: 'Add Admin',
  ChannelAddSubscribers: 'Add Subscribers',
  ChannelCreator: 'Owner',
  'ChannelDirectMessages.Settings.Title': 'Direct Messages',
  ChannelJoin: 'JOIN',
  ChannelLinkInfo: 'Anyone who has Telegram installed will be able to join your channel by following this link.',
  ChannelPrivate: 'Private Channel',
  ChannelPrivateInfo: 'Private channels can only be joined via an invite link.',
  ChannelPrivateLinkHelp: 'People can join your channel by following this link. You can revoke the link any time.',
  ChannelPublic: 'Public Channel',
  ChannelPublicInfo: 'Public channels can be found in search, anyone can join them.',
  ChannelPermissions: 'Permissions',
  ChannelPermissionsHeader: 'What can members of this group do?',
  ChannelSettingsJoinRequest: 'Approve new members',
  ChannelSignMessages: 'Sign Messages',
  ChannelSignMessagesInfo: 'Add names of admins to the messages they post',
  ChannelSignMessagesWithProfile: 'Show Authors\' Profiles',
  ChannelSignProfilesInfo: 'Add names and photos of admins to the messages they post, linking to their profiles.',
  ChannelType: 'Channel Type',
  'Chat.Accessory.Edit': 'Edit message',
  // ЗАДАЧА 6, плашка пересылки в композере. У оригинала обе надписи — ФОРМЫ ЧИСЛА со
  // счётчиком внутри (`Chat.Accessory.Forward`, `Chat.Accessory.Hidden`), а наша плашка
  // печатает надпись БЕЗ числа и держит два готовых варианта. Ключ оригинала за нашей
  // строкой не закреплён по тому же правилу, что и `*Suffix` (задача 1): кодмод подставил
  // бы в место без числа строку с `%d`, и `%d` нарисовался бы буквой.
  //
  // Пока задача 6 не правит вызывающего (`components/composer`), расхождение такое:
  //  • `Chat.Accessory.Forward` — КЛЮЧ-СИРОТА: текст оригинала есть, вызывающих и
  //    переводов ноль. Сиротой он перестанет быть, когда плашка начнёт звать его с числом;
  //  • `Chat.Accessory.Forward.Hidden` — наша ПЛОСКАЯ строка там, где у оригинала
  //    плюральный `Chat.Accessory.Hidden` (`{one_value: 'Forward Message (sender\'s name
  //    hidden)', other_value: 'Forward %d Messages (senders\' names hidden)'}`, tweb
  //    lang.ts:3436). Имя ключа наше, поэтому сверка с оригиналом её и не ловит;
  //  • `Chat.Accessory.Forward.One` / `.Many` — наши варианты без числа, они и уедут.
  'Chat.Accessory.Forward': { one_value: 'Forward Message', other_value: 'Forward %d Messages' },
  'Chat.Accessory.Forward.Hidden': 'Forward Message (sender name hidden)',
  'Chat.Accessory.Forward.Many': 'Forward Messages',
  'Chat.Accessory.Forward.One': 'Forward Message',
  'Chat.Accessory.Reply': 'Reply to',
  'Chat.Alert.Forward.Action.Another': 'Forward to Another Chat',
  'Chat.Alert.Forward.HideCaption': 'Hide caption',
  'Chat.Alert.Forward.HideSenderName': 'Hide sender name',
  'Chat.Alert.Forward.ShowCaption': 'Show caption',
  'Chat.Alert.Forward.ShowSenderName': 'Show sender name',
  'Chat.ClearHistory.Text': 'Are you sure you want to clear history?',
  'Chat.Close': 'Close Chat',
  'Chat.CommentsLabel': 'Comments',
  'Chat.Context.LinkCopiedPrivate': 'Link copied. This link will only work for chat members.',
  'Chat.Context.ReadLabel': 'Read',
  'Chat.Context.ReadShowWhen': 'show when',
  'Chat.Context.ReactedLabel': 'Reacted',
  'Chat.Context.SearchSelected': 'Search Selected',
  'Chat.Context.SeenBy': 'Seen by',
  'Chat.ContextMenu.Read': 'Read',
  'Chat.CopySelectedText': 'Copy Selected Text',
  'Chat.Date.ScheduledForToday': 'Scheduled for today',
  'Chat.Delete.Channel.Text': 'The channel will be deleted for all subscribers.',
  'Chat.Delete.Group.Text': 'The group will be deleted for all members.',
  'Chat.Delete.Private.Text': 'This chat will be deleted from your chat list.',
  'Chat.DropAsFilesDesc': 'without compression',
  'Chat.DropQuickDesc': 'in a quick way',
  'Chat.DropTitle': 'Drop files here to send them',
  'Chat.ForwardedFrom': 'Forwarded from',
  'Chat.Frozen.LearnMore': 'Learn more...',
  'Chat.Input.Attach.Document': 'Document',
  'Chat.Input.Attach.PhotoOrVideo': 'Photo or Video',
  'Chat.Input.FrozenButton1': 'Your Account is Frozen',
  'Chat.Input.FrozenButton2': 'Click to view details',
  'Chat.Input.UnpinAll': 'Unpin All Messages',
  'Chat.Leave.Channel.Text': 'Are you sure you want to leave this channel?',
  'Chat.Leave.Group.Text': 'Are you sure you want to leave this group?',
  'Chat.LeaveChat': 'Leave chat',
  'Chat.Menu.ChangeTheme': 'Change Theme',
  'Chat.Menu.ClearSelection': 'Clear Selection',
  'Chat.Menu.SelectMessages': 'Select Messages',
  'Chat.Menu.SendGift': 'Send a Gift',
  'Chat.MuteChat': 'Mute Chat',
  'Chat.OwnerBadge': 'owner',
  'Chat.Poll.Stop': 'Stop Poll',
  'Chat.Poll.SubmitVote': 'Vote',
  'Chat.Poll.TotalVotesEmpty': 'No votes yet',
  'Chat.Poll.TotalVotesResultEmpty': 'No votes',
  'Chat.Poll.Type.Anonymous': 'Anonymous Poll',
  'Chat.Poll.Type.AnonymousQuiz': 'Anonymous Quiz',
  'Chat.Poll.Type.Closed': 'Final Results',
  'Chat.Poll.Type.Quiz': 'Quiz',
  'Chat.Poll.Unvote': 'Retract Vote',
  'Chat.Poll.VotedSuffix': 'voted',
  'Chat.Quiz.AnsweredSuffix': 'answered',
  'Chat.Search.NothingFound': 'Nothing interesting here yet...',
  'Chat.Selection.Selected': 'Selected',
  'Chat.Send.ScheduledMessage': 'Schedule Message',
  'Chat.Send.SetReminder': 'Set a Reminder',
  'Chat.Send.WithoutSound': 'Send Without Sound',
  'Chat.SendAs.Anonymously': 'Anonymously',
  'Chat.SendAs.PersonalAccount': 'personal account',
  'Chat.SendAs.Title': 'Send As…',
  'Chat.SendAs.YourChannels': 'Your channels',
  'Chat.Service.Call.Missed': 'Missed',
  'Chat.UnpinAll.Text': 'Are you sure you want to unpin all messages?',
  ChatAdmin: 'admin',
  'ChatBackground.Blurred': 'Blurred Image',
  'ChatBackground.Reset': 'Reset to Default',
  'ChatBackground.Title': 'Chat Background',
  'ChatBackground.Upload': 'Upload Image',
  ChatHistory: 'Chat history for new members',
  ChatHistoryHint: 'New members will see earlier messages when this is on.',
  'ChatList.Context.DeleteChat': 'Delete Chat',
  'ChatList.Context.LeaveChannel': 'Leave Channel',
  'ChatList.Context.LeaveGroup': 'Leave Group',
  'ChatList.Context.Mute': 'Mute',
  'ChatList.Context.Pin': 'Pin',
  'ChatList.Context.Preview': 'Preview',
  'ChatList.Context.Unmute': 'Unmute',
  'ChatList.Context.Unpin': 'Unpin',
  'ChatList.Filter.Channels': 'Channels',
  'ChatList.Filter.Confirm.Remove.Header': 'Remove Folder',
  'ChatList.Filter.Confirm.Remove.Text': 'Are you sure you want to remove this folder? Your chats will not be deleted.',
  'ChatList.Filter.Groups': 'Groups',
  'ChatList.Filter.Header': 'Create folders for different groups of chats and quickly switch between them.',
  'ChatList.Filter.Include.AddChat': 'Add Chats',
  'ChatList.Filter.List.Title': 'Chat Folders',
  'ChatList.Filter.MutedChats': 'Muted',
  'ChatList.Filter.NewTitle': 'Create Folder',
  'ChatList.Filter.NonContacts': 'Non-Contacts',
  'ChatList.Mute.1Day': 'For 1 Day',
  'ChatList.Mute.1Hour': 'For 1 Hour',
  'ChatList.Mute.3Days': 'For 3 Days',
  'ChatList.Mute.4Hours': 'For 4 Hours',
  'ChatList.Mute.8Hours': 'For 8 Hours',
  'ChatList.Service.Call.Missed': 'Missed Call',
  'ChatTheme.None': 'No Theme',
  'ChatTheme.Title': 'Chat Theme',
  ChatYourSelf: 'forward here to save',
  ChatYourSelfDescription1: 'Forward messages here to save them',
  ChatYourSelfDescription2: 'Send media and files to store them',
  ChatYourSelfDescription3: 'Access this chat from any device',
  ChatYourSelfDescription4: 'Use search to quickly find things',
  ChatYourSelfTitle: 'Your cloud storage',
  'Checkbox.Disabled': 'Disabled',
  'Checkbox.Enabled': 'Enabled',
  Checklist: 'Checklist',
  'Checklist.AddTask': 'Add a Task',
  'Checklist.NewTask': 'New task',
  'Checklist.Tasks': 'Tasks',
  'Checklist.Title.Label': 'Title',
  'Checklist.TitlePlaceholder': 'Checklist Title',
  ChecklistAllowOthersAdd: 'Allow Others to Add Tasks',
  ChecklistAllowOthersDone: 'Allow Others to Mark as Done',
  'Checkout.PasswordEntry.Pay': 'Pay',
  Clear: 'Clear',
  ClearOtherSessionsHelp: 'Logs out all devices except for this one.',
  ClearRecentStickersAlertTitle: 'Clear recent stickers',
  Close: 'Close',
  'CloseFriends.Title': 'Close Friends',
  'CloseFriends.Updated': 'Close friends list updated',
  CloseTopic: 'Close topic',
  ColorTheme: 'Color theme',
  Comment: 'Comment',
  'Common.Back': 'Back',
  'Common.Creating': 'Creating…',
  'Common.DoneSuffix': 'done',
  'Common.Menu': 'Menu',
  'Common.Of': 'of',
  'Common.Tag': 'Tag',
  'Compose.NewMessage': 'New Message',
  'Composer.CancelRecording': 'Cancel Recording',
  'Composer.DiscardVoice.Text': 'Are you sure you want to discard this voice message?',
  'Composer.Formatting': 'Formatting',
  'Composer.MediaRestricted': 'Media is not allowed in this group',
  'Composer.MessageEffect': 'Message effect',
  'Composer.RecordRound': 'Record video message',
  'Composer.RecordVoice': 'Record voice message',
  'ConnectionStatus.ReconnectInPlain': 'Reconnect in %ds',
  'ConnectionStatus.Reconnecting': 'Reconnecting...',
  'ConnectionStatus.Waiting': 'Waiting for network...',
  Contacts: 'Contacts',
  'Contacts.Empty': 'No contacts',
  'Contacts.NotFound': 'No contacts found.',
  Continue: 'Continue',
  Copy: 'Copy',
  CopyLink: 'Copy Link',
  Country: 'Country',
  Create: 'Create',
  'CreateBot.Username.Taken': 'This username is already taken.',
  'CreateGroup.NameHolder': 'Group Name',
  CreateNewLink: 'Create a New Link',
  CurrentSession: 'This device',
  DarkMode: 'Dark Mode',
  DataSettings: 'Data and Storage',
  Days: {
    one_value: '%1$d day',
    other_value: '%1$d days',
  },
  Delete: 'Delete',
  'DeleteAccount.Action': 'Delete My Account',
  'DeleteAccount.Caption': 'This will delete your account and all your data. Your messages will remain but appear as sent by a «Deleted Account».',
  'DeleteAccount.Text': 'Are you sure you want to delete your account? This action cannot be undone.',
  'DeleteAccount.Title': 'Delete Account',
  DeleteAllRevokedLinks: 'Delete All Revoked Links',
  DeleteAlsoFor: 'Also delete for',
  DeleteAndExitButton: 'Delete and Leave Group',
  'DeleteChat.DeleteGroupForAll': 'Delete for all members',
  DeleteForEveryone: 'Delete for everyone',
  DeleteForMe: 'Delete for me',
  DeleteMessagesCount: {
    one_value: 'Delete %d message',
    other_value: 'Delete %d messages',
  },
  DeleteMega: 'Delete Group',
  DeleteSingleMessagesTitle: 'Delete message',
  DeleteStorySubtitle: 'Are you sure you want to delete this story?',
  DeleteStoryTitle: 'Delete Story',
  DeletedMessage: 'Deleted message',
  DescriptionOptionalPlaceholder: 'Description (optional)',
  DescriptionPlaceholder: 'Description',
  Devices: 'Devices',
  Disable: 'Disable',
  DisableAnimations: 'Disable Animations',
  DisablePhotoSpoiler: 'Remove spoiler',
  DisableSharing: 'Disable Sharing',
  Discard: 'Discard',
  DiscardVoiceMessageTitle: 'Discard Voice Message',
  'Discussion.Link.Question': 'Do you want to set %1$s as the discussion board for this channel?',
  'Discussion.Linked': 'Users can now discuss your posts in the linked group.',
  'Discussion.Unlink.Text': 'Are you sure you want to unlink this group from the channel?',
  DiscussionChannelHelp3: 'Select a group chat that will host comments from your channel.',
  DiscussionCreateGroup: 'Create a New Group',
  DiscussionInfo: 'Add a group chat for comments',
  DiscussionLinkGroup: 'Link Group',
  DiscussionStarted: 'Discussion started',
  DiscussionUnlink: 'Unlink',
  DiscussionUnlinkGroup: 'Unlink Group',
  DoNotForward: 'Do Not Forward',
  DoNotTranslate: 'Do Not Translate',
  DoubleTapSetting: 'Quick Reaction',
  DoubleTapSettingInfo: 'Double-tap a message to send this reaction quickly.',
  Draft: 'Draft',
  DynamicPackOrder: 'Dynamic Pack Order',
  Edit: 'Edit',
  'EditAccount.Logout': 'Log Out',
  'EditAccount.Title': 'Edit Profile',
  EditAdmin: 'Admin Rights',
  EditAdminWhatCanDo: 'What can this admin do?',
  EditFactCheck: 'Edit Fact Check',
  'EditFolder.Toast.ChooseChat': 'Please choose at least one chat for this folder.',
  'EditContact.PhotoHint': 'You can suggest a new profile photo to your contact — or change their photo just for yourself.',
  'EditProfile.AddBirthdayRow': 'Add Birthday',
  'EditProfile.BioLabel': 'Bio (optional)',
  'EditProfile.FirstNameLabel': 'Name',
  'EditProfile.Username.Available': 'Username is available',
  'EditProfile.Username.Caption': 'You can choose a public username so people can find you and contact you without knowing your phone number.',
  'EditProfile.Username.Checking': 'Checking…',
  'EditProfile.Username.Label': 'Username (optional)',
  'EditProfile.Username.Rules': 'Username must be 5–32 chars: letters, digits, underscore.',
  'EditProfile.Username.Taken': 'Username is already taken',
  'EditProfile.Username.TooShort': 'Minimum 5 characters.',
  'EditProfile.VideoError': 'Could not process this video.',
  EditedMessage: 'edited',
  'Effect.Remove': 'Remove Effect',
  'Emoji.Activity': 'Activity',
  'Emoji.AnimalsAndNature': 'Animals & Nature',
  'Emoji.Flags': 'Flags',
  'Emoji.FoodAndDrink': 'Food & Drink',
  'Emoji.Objects': 'Objects',
  'Emoji.Recent': 'Frequently Used',
  'Emoji.SmilesAndPeople': 'Smileys & People',
  'Emoji.Symbols': 'Symbols',
  'Emoji.TravelAndPlaces': 'Travel & Places',
  'EmojiStatus.Set': 'Set Emoji Status',
  EnableAnimations: 'Enable Animations',
  EnablePhotoSpoiler: 'Hide with spoiler',
  EnterChannelName: 'Channel name',
  'Error.AnError': 'An error occurred. Please try again later.',
  'Error.SomethingWentWrong': 'Something went wrong',
  Exceptions: 'Exceptions',
  'ExportedInvitation.Status.Expired': 'expired',
  'ExportedInvitation.Status.Revoked': 'revoked',
  FactCheck: 'Fact Check',
  'FactCheck.AdminNote': 'This fact check was added by an admin.',
  'FactCheck.CountryPlaceholder': 'Country code (optional)',
  'FactCheck.Delete': 'Delete Fact Check',
  FactCheckPlaceholder: 'Add Fact or Context',
  FavoriteStickers: 'Favorites',
  FilterAllChats: 'All Chats',
  FilterAllChatsShort: 'All',
  FilterChatTypes: 'Chat types',
  FilterChats: 'Chats',
  FilterEdit: 'Edit folder',
  FilterEditAll: 'Edit folders',
  FilterExclude: 'Excluded Chats',
  FilterExcludeInfo: 'Choose chats or types of chats that will not appear in this folder.',
  FilterHeaderEdit: 'Edit Folder',
  FilterInclude: 'Included Chats',
  FilterIncludeExcludeInfo: 'Choose chats and types of chats that will\nappear and never appear in this folder.',
  FilterIncludeInfo: 'Choose chats or types of chats that will appear in this folder.',
  FilterNameHint: 'Folder name',
  FilterNew: 'New Folder',
  FilterPersonal: 'Personal',
  FilterPersonalDescription: 'Messages from private chats.',
  FilterRecommended: 'Recommended Folders',
  FilterRemoveChats: 'Remove Chats',
  FilterUnreadDescription: 'Chats with new messages.',
  Filters: 'Folders',
  FiltersOnLeft: 'Folders on the Left',
  FiltersOnTop: 'Folders above chats',
  FiltersView: 'Folders view',
  FirstName: 'First name (required)',
  'Folder.Added': 'Folder added',
  'Folder.Invite.Adding': 'Adding…',
  'Folder.Invite.Invalid': 'This link is invalid or has expired.',
  'Folder.Invite.Question.Folder': 'Do you want to add the folder «%1$s»?',
  'Folder.Invite.Question': 'Do you want to add «%1$s» and join its chats?',
  'Folder.Share.Empty': 'This folder has no chats to share.',
  'ForumTopic.Closed': 'Topic is closed',
  'ForumTopic.Context.New': 'Create Topic',
  'ForumTopic.Context.ShowAsMessages': 'View as Messages',
  'ForumTopic.Created': 'Topic created',
  'ForumTopic.EnableHint': 'Group members can discuss different topics in separate threads.',
  'ForumTopic.Hidden': 'Hidden Topics',
  'ForumTopic.Name.Placeholder': 'Topic Name',
  'ForumTopic.Title.Edit': 'Edit Topic',
  'ForumTopic.Unhide': 'Unhide',
  Forward: 'Forward',
  FromYou: 'You',
  General: 'General',
  'General.NightMode': 'Night Mode',
  'General.TextSize': 'Text Size',
  'General.TimeFormat': 'Time Format',
  'General.TimeFormat.h12': '12-hour',
  'General.TimeFormat.h23': '24-hour',
  'GeneralSettings.EmojiPrediction': 'Suggest Emoji',
  'Gif.Delete': 'Delete GIF',
  'Gif.Save': 'Save GIF',
  'Gif.Saved': 'GIF saved to your GIFs.',
  'Gif.Trending': 'Trending',
  'Giveaway.Create': 'Create Giveaway',
  'Giveaway.DurationHint': 'Giveaway can last up to 7 days.',
  'Giveaway.New': 'New Giveaway',
  'Giveaway.Participate': 'Participate',
  'Giveaway.Participating': 'You are participating',
  'Giveaway.Prize': 'Prize',
  'Giveaway.StarsPerWinner': 'Stars per winner',
  'Giveaway.WinnersSelected': 'Winners selected',
  'Giveaway.YouWon': 'You won the giveaway!',
  GlobalSearch: 'Global search',
  GlobalSendMessageRestricted: 'Sending messages is not allowed in this group.',
  Group: 'Group',
  'Group.MemberBadge': 'Member',
  'Group.RestrictedBadge': 'Restricted',
  GroupAddMembers: 'Add Members',
  'GroupCall.Banner.Join': 'Join',
  'GroupCall.Participants': 'Participants',
  GroupChecklist: 'Group Checklist',
  'GroupPermissions.PaidMessages': 'Paid messages',
  'GroupPermissions.PaidMessages.Hint': 'Charge stars per message from non-admins. 0 disables paid messages.',
  'GroupPermissions.StarsPerMessage': 'Stars per message',
  GroupType: 'Group Type',
  Hide: 'Hide',
  'InactiveChannel.Broadcast': 'channel',
  'InactiveChannel.Group': 'group',
  Info: 'Info',
  'InstalledStickers.LoopAnimated': 'Loop Animated Stickers',
  'InstantView.OpenInBrowser': 'Open in browser',
  InviteLink: 'Invite Link',
  InviteLinks: 'Invite Links',
  'InviteLinks.Additional': 'Additional Links',
  'InviteLinks.CanJoinSuffix': 'can join',
  'InviteLinks.Caption': 'You can create additional invite links and revoke them at any time.',
  'InviteLinks.Description.Group': 'Anyone who has Telegram installed will be able to join your group by following this link.',
  'InviteLinks.Description.Additional': 'You can create additional invite links that are limited by time, number of users, or require a paid subscription.',
  'InviteLinks.TimeLimitHelp': 'You can make the link expire after a certain time.',
  'InviteLinks.UsesLimitHelp': 'You can make the link work only for a certain number of users.',
  'InviteLinks.Edit': 'Edit Link',
  'InviteLinks.Expires': 'Expires',
  'InviteLinks.JoinedSuffix': 'joined',
  'InviteLinks.LimitPeriod': 'Limit by Period',
  'InviteLinks.LimitReached': 'limit reached',
  'InviteLinks.LimitUses': 'Limit Number of Uses',
  'InviteLinks.NameLabel': 'Link Name',
  'InviteLinks.RemainingSuffix': 'remaining',
  'InviteLinks.UsageHintSuffix': 'people can join via this link.',
  'InviteLinks.View': 'View link',
  JumpToDate: 'Jump to Date',
  'KeyboardShortcuts.Action.Bold': 'Bold',
  'KeyboardShortcuts.Action.ClosePopup': 'Close popup or menu',
  'KeyboardShortcuts.Action.EditLast': 'Edit last message',
  'KeyboardShortcuts.Action.Exit': 'Exit',
  'KeyboardShortcuts.Action.HistoryEnd': 'Go to End of History',
  'KeyboardShortcuts.Action.HistoryStart': 'Go to Beginning of History',
  'KeyboardShortcuts.Action.Italic': 'Italic',
  'KeyboardShortcuts.Action.Link': 'Add Link',
  'KeyboardShortcuts.Action.LockApp': 'Lock the App',
  'KeyboardShortcuts.Action.Monospace': 'Monospace',
  'KeyboardShortcuts.Action.NewLine': 'New line',
  'KeyboardShortcuts.Action.NextChat': 'Next chat',
  'KeyboardShortcuts.Action.NextMedia': 'Next media',
  'KeyboardShortcuts.Action.NextStory': 'Next story',
  'KeyboardShortcuts.Action.PlayPause': 'Play/Pause',
  'KeyboardShortcuts.Action.PreviousChat': 'Previous chat',
  'KeyboardShortcuts.Action.PreviousMedia': 'Previous media',
  'KeyboardShortcuts.Action.PreviousStory': 'Previous story',
  'KeyboardShortcuts.Action.Redo': 'Redo',
  'KeyboardShortcuts.Action.ReplyToPrevious': 'Reply to previous message',
  'KeyboardShortcuts.Action.Spoiler': 'Spoiler',
  'KeyboardShortcuts.Action.Strikethrough': 'Strikethrough',
  'KeyboardShortcuts.Action.Underline': 'Underline',
  'KeyboardShortcuts.Hint.PasscodeNotSet': 'Passcode is configured in Privacy settings',
  'KeyboardShortcuts.Hint.WhenInputEmpty': 'when input is empty',
  'KeyboardShortcuts.Section.Chat': 'Chat',
  'KeyboardShortcuts.Section.Formatting': 'Text Formatting',
  'KeyboardShortcuts.Section.MediaViewer': 'Media Viewer',
  'KeyboardShortcuts.Section.Messages': 'Messages',
  'KeyboardShortcuts.Section.Navigation': 'Navigation',
  'KeyboardShortcuts.Section.PhotoEditor': 'Photo Editor',
  'KeyboardShortcuts.Section.Stories': 'Stories',
  'KeyboardShortcuts.Title': 'Keyboard Shortcuts',
  KickFromGroup: 'Remove from group',
  LastName: 'Last name (optional)',
  LastSeenTitle: 'Who can see my Last Seen time?',
  Lately: 'last seen recently',
  LinkCopied: 'Link copied to clipboard',
  LinkInvalid: 'Invalid link.',
  LinkNameHelp: 'Only admins will see this name.',
  LinkNameHint: 'Link Name (Optional)',
  LinkTaken: 'This link is already taken.',
  'LiteMode.Caption': 'Disable animations and effects to reduce power usage.',
  'LiteMode.Key.animations.Title': 'Interface Animations',
  'LiteMode.Key.background_animation.Title': 'Chat background animation',
  'LiteMode.Key.chat_spoilers.Title': 'Animated spoiler effect',
  'LiteMode.Key.effects_reactions.Title': 'Reaction effect',
  'LiteMode.Key.emoji.Title': 'Emoji Animations',
  'LiteMode.Key.gif.Title': 'Autoplay GIFs',
  'LiteMode.Key.video.Title': 'Autoplay Videos',
  'LiteMode.Title': 'Power Saving',
  'Livestream.Ended': 'Ended',
  'Livestream.IsLive': 'The stream is live',
  'Livestream.Recording': 'Recording',
  'Livestream.Start': 'Start Live Stream',
  Loading: 'Loading...',
  'Login.ByPasskey': 'Log in by passkey',
  'Login.ByPhone': 'Log in by phone number',
  'Login.Code.Expired': 'Code expired. Please request a new one.',
  'Login.Code.SentSms': 'We have sent you an SMS\nwith the code.',
  'Login.Error.FloodWait': 'Too many attempts. Please try again later.',
  'Login.Error.Generic': 'Something went wrong. Try again.',
  'Login.ForgotPassword': 'Forgot Password?',
  'Login.Next': 'Next',
  'Login.Passkey.Action': 'Log in with a Passkey',
  'Login.Passkey.Failed': 'Passkey sign-in failed',
  'Login.Password.Subtitle': 'Your account is protected with\nan additional password',
  'Login.Password.SubtitleFlat': 'Your account is protected with an additional password.',
  'Login.Password.Title': 'Enter Your Password',
  'Login.PhoneInvalid': 'Invalid phone number.',
  'Login.PhoneLabel': 'Phone Number',
  'Login.PhoneLabelInvalid': 'Phone Number Invalid',
  'Login.QR.Help1': 'Open Telegram on your phone',
  'Login.QR.Help2': 'Go to **Settings** > **Devices** > **Add Device**',
  'Login.QR.Help3': 'Point your phone at this screen to confirm login',
  'Login.QR.Subtitle': 'Scan with Telegram app on your phone',
  'Login.QR.Title': 'Log in by QR Code',
  'Login.Register.LastName.Placeholder': 'Last Name',
  'Login.Register.NameRequired': 'Please enter your name',
  'Login.Register.NameTooLong': 'Name is too long',
  'Login.Register.Subtitle': 'Enter your name and add\na profile photo',
  'Login.ResetAccount.Text': 'This action can\'t be undone.\n\nIf you reset your account, all your messages and chats will be deleted.',
  'Login.ResetAccount.Title': 'Warning',
  'Login.ResetAccountFail.Title': 'Sorry',
  'Login.ResetPassword.CodeHint': 'Enter the code we just sent to your email',
  'Login.ResetPassword.HasEmail': 'A recovery email is linked to this account — reset it by email instead.',
  'Login.ResetPassword.NoEmailText': 'Since you didn\'t provide a recovery email when setting up your password, your remaining options are either to remember your password or to reset your account.',
  'Login.ResetPassword.ResetAccount': 'Reset Account',
  'Login.ResetPassword.Title': 'Reset Password',
  'Login.SessionExpired': 'Session expired. Please sign in again.',
  'Login.StartText': 'Please confirm your country code\nand enter your phone number.',
  'Login.Title': 'Sign in to Telegram',
  LoginEmail: 'Login Email',
  'LoginEmail.Caption': 'This email is used to log in if you lose access to your number.',
  'LoginEmail.Change': 'Change Login Email',
  LoginPassword: 'Password',
  'ManageLinks.DeleteAll.Confirm': 'Are you sure you want to delete all revoked links?',
  MarkAsUnread: 'Mark as unread',
  'MarkupTooltip.LinkPlaceholder': 'Enter URL...',
  'Media.Pause': 'Pause',
  'Media.Play': 'Play',
  'MediaEditor.Adjustments.Brightness': 'Brightness',
  'MediaEditor.Adjustments.Contrast': 'Contrast',
  'MediaEditor.Adjustments.Fade': 'Fade',
  'MediaEditor.Adjustments.Grain': 'Grain',
  'MediaEditor.Adjustments.Highlights': 'Highlights',
  'MediaEditor.Adjustments.Enhance': 'Enhance',
  'MediaEditor.Adjustments.Saturation': 'Saturation',
  'MediaEditor.Adjustments.Shadows': 'Shadows',
  'MediaEditor.Adjustments.Sharpen': 'Sharpen',
  'MediaEditor.Adjustments.Vignette': 'Vignette',
  'MediaEditor.Adjustments.Warmth': 'Warmth',
  'MediaEditor.AspectRatio': 'Aspect ratio',
  'MediaEditor.Brushes.Arrow': 'Arrow',
  'MediaEditor.Brushes.Blur': 'Blur',
  'MediaEditor.Brushes.Brush': 'Marker',
  'MediaEditor.Brushes.Eraser': 'Eraser',
  'MediaEditor.Brushes.Neon': 'Neon',
  'MediaEditor.Brushes.Pen': 'Pen',
  'MediaEditor.BrushSize': 'Brush size',
  'MediaEditor.Cover': 'Cover',
  'MediaEditor.Crop': 'Crop',
  'MediaEditor.Discard.Text': 'Are you sure you want to discard the changes?',
  'MediaEditor.DiscardChanges': 'Discard Changes',
  'MediaEditor.Draw': 'Draw',
  'MediaEditor.Flip': 'Flip',
  'MediaEditor.Font': 'Font',
  'MediaEditor.Free': 'Free',
  'MediaEditor.Original': 'Original',
  'MediaEditor.RecentlyUsed': 'Recently Used',
  'MediaEditor.Rotate': 'Rotate',
  'MediaEditor.Square': 'Square',
  'MediaEditor.TextSize': 'Text size',
  'MediaEditor.Tool': 'Tool',
  'MediaViewer.Context.CopyMedia': 'Copy Media',
  'MediaViewer.Context.Download': 'Download',
  'MediaViewer.CopyError': 'Could not copy the image',
  'MediaViewer.ImageCopied': 'Image copied to clipboard',
  MediaZoomIn: 'Zoom In',
  MediaZoomOut: 'Zoom Out',
  MegaPrivate: 'Private Group',
  MegaPrivateInfo: 'Private groups can only be joined if you were invited or have an invite link.',
  MegaPrivateLinkHelp: 'People can join your group by following this link. You can revoke the link any time.',
  MegaPublic: 'Public Group',
  MegaPublicInfo: 'Public groups can be found in search, chat history is available to everyone and anyone can join.',
  Members: {
    one_value: '%1$d member',
    other_value: '%1$d members',
  },
  Message: 'Message',
  'Message.Context.Pin': 'Pin',
  'Message.Context.Select': 'Select',
  'Message.Context.Unpin': 'Unpin',
  'Message.Preview.Call': 'Call',
  'Message.Unsupported': 'Unsupported message',
  'MessageContext.CopyMessageLink1': 'Copy Message Link',
  MessagePreview: 'Message Preview',
  MessageScheduleEditTime: 'Reschedule',
  MessageScheduleSend: 'Send Now',
  MessageScheduledUntilOnline: 'Scheduled until online',
  'MiniApps.AppsMore': 'Show more',
  Months: {
    one_value: '%1$d month',
    other_value: '%1$d months',
  },
  MoreBoosts: {
    one_value: '**%d** more boost',
    other_value: '**%d** more boosts',
  },
  MoreSimilar: 'More Channels',
  'MultiAccount.AddAccount': 'Add Account',
  'MultiAccount.More': 'More',
  MyNotes: 'My Notes',
  'MyStories.Archive.Empty': 'No archived stories',
  'MyStories.Archive.Title': 'Stories Archive',
  'MyStories.Title': 'My Stories',
  Never: 'Never',
  New: 'New',
  NewChannel: 'New Channel',
  NewChecklist: 'New Checklist',
  'NewChecklist.TaskPlaceholder': 'Task',
  NewGroup: 'New Group',
  NewLink: 'New Link',
  NewPoll: 'New Poll',
  'NewPoll.Anonymous': 'Anonymous Voting',
  'NewPoll.MultipleChoice': 'Multiple Answers',
  'NewPoll.Option': 'Option',
  'NewPoll.OptionsAddOption': 'Add an Option',
  'NewPoll.Quiz': 'Quiz Mode',
  'NewPoll.QuizHint': 'Select the correct answer in the list of options.',
  NewPrivateChat: 'New Private Chat',
  NewTopic: 'New Topic',
  NoEmojiFound: 'No emoji found',
  NoGIFsFound: 'No GIFs found',
  NoMessages: 'No messages here yet...',
  NoMessagesGreetingsDescription: 'Send a message or tap the greeting below.',
  NoReactions: 'No reactions',
  NoResult: 'No results',
  NoScheduledMessages: 'No scheduled messages here yet...',
  NoStickersFound: 'No stickers found',
  NoTopics: 'No topics',
  NobodyViewed: 'Nobody viewed',
  Notifications: 'Notifications',
  'Notifications.Count': { one_value: '%d notification', other_value: '%d notifications' },
  'Notifications.Default': 'Give Telegram permission to send notifications. You may need to refresh the page to see the changes.',
  'Notifications.Enable': 'Enable Notifications',
  'Notifications.New': 'New notification',
  'Notifications.Offline': 'Show offline notifications',
  'Notifications.Show': 'Show notifications',
  'Notifications.Sound': 'Notification Sound',
  'Notifications.Sound.Caption': 'Drag and release or click to test the volume.',
  'Notifications.Sound.Effects': 'Sound Effects',
  'Notifications.Sound.Section': 'Sound',
  'Notifications.Sound.Sent': 'Message Sent',
  'Notifications.Sound.Volume': 'Sound Volume',
  'Notifications.Web': 'Web Notifications',
  NotificationsForChannels: 'Notifications for channels',
  NotificationsForGroups: 'Notifications for groups',
  NotificationsForPrivateChats: 'Notifications for private chats',
  OK: 'OK',
  Off: 'Off',
  Online: 'online',
  OnlyAllowThisReactions: 'Only allow these reactions',
  OpenChat: 'Open Chat',
  OpenInNewTab: 'Open in new tab',
  Other: 'Other',
  OtherSessions: 'Active sessions',
  PASSWORD_HASH_INVALID: 'Incorrect password',
  PHONE_CODE_INVALID: 'Invalid code',
  'PrivacySettingsController.UserCount': {
    one_value: '%d user',
    other_value: '%d users',
  },
  'PWA.Install': 'Install App',
  'PaidMedia.MakePaid': 'Make paid',
  'PaidMedia.NotEnoughStars': 'Not enough Stars to unlock',
  'PaidMedia.PriceHint': 'Set a price in Stars — recipients unlock the media by paying you.',
  'PaidMedia.Title': 'Paid Content',
  'PaidMedia.UnlockFor': 'Unlock for',
  'PaidMedia.Unlocking': 'Unlocking…',
  'PasscodeLock.AutoLock': 'Auto-lock after',
  'PasscodeLock.AutoLock.Caption': 'Automatically lock the app if you are away for some time.',
  'PasscodeLock.ChangePasscode': 'Change passcode',
  'PasscodeLock.Description': 'When a passcode is set, a lock icon appears above your chat list. Tap it to lock your Telegram.',
  'PasscodeLock.EnterANewPasscode': 'Enter a new passcode',
  'PasscodeLock.EnterAPasscode': 'Enter a passcode',
  'PasscodeLock.EnterYourPasscode': 'Enter your passcode',
  'PasscodeLock.ForgotNotice': 'Note: if you forget your passcode, you\'ll need to log out and log in again.',
  'PasscodeLock.ForgotPasscode.Text': 'If you forgot your passcode, you need to log out and log in again.',
  'PasscodeLock.Item.Title': 'Passcode Lock',
  'PasscodeLock.LockNow': 'Lock the app',
  'PasscodeLock.Logout.Text': 'Are you sure you want to log out? You will need to sign in again.',
  'PasscodeLock.PasscodeHasBeenChanged': 'Passcode has been changed.',
  'PasscodeLock.PasscodeHasBeenDisabled': 'Passcode has been disabled.',
  'PasscodeLock.PasscodeHasBeenSet': 'Passcode has been set.',
  'PasscodeLock.PasscodesDontMatch': 'Passcodes don’t match, try again',
  'PasscodeLock.Proceed': 'Proceed',
  'PasscodeLock.ReEnterPasscode': 'Re-enter the passcode',
  'PasscodeLock.SetPasscode': 'Set passcode',
  'PasscodeLock.Title': 'Passcode',
  'PasscodeLock.TooManyAttempts': 'Too many attempts, try again later',
  'PasscodeLock.TurnOff': 'Turn Off',
  'PasscodeLock.TurnOff.Description': 'Are you sure you want to turn passcode off?',
  'PasscodeLock.TurnOff.Title': 'Turn Passcode Off',
  'PasscodeLock.TurnOn': 'Turn Passcode On',
  'PasscodeLock.WrongPasscodeShort': 'Wrong passcode',
  'Passkey.CreateError': 'Could not create a passkey.',
  'Passkey.Row1.Subtitle': 'Make a passkey to log in easily and safely.',
  'Passkey.Row1.Title': 'Create a Passkey',
  'Passkey.Row2.Subtitle': 'Use Face ID, Touch ID, or your passcode to log in.',
  'Passkey.Row2.Title': 'Log in with Face ID',
  'Passkey.Row3.Subtitle': 'Your passkey is safely kept in your iCloud Keychain.',
  'Passkey.Row3.Title': 'Store Passkey Securely',
  'Passkey.Subtitle': 'Log in safely and keep your account secure.',
  'Passkey.Title': 'Protect your account',
  'Passkey.Unsupported': 'UNSUPPORTED',
  'Passkeys.Add': 'Add a Passkey',
  'Passkeys.Caption': 'Passkeys let you sign in without a password, using your fingerprint, face or device PIN.',
  'Passkeys.Created': 'Created',
  'Passkeys.Item': 'Passkey',
  'Passkeys.LastUsed': 'Last used',
  'Passkeys.Unsupported': 'Passkeys are not supported in this browser.',
  PasswordAsHintError: 'Hint must be different from your password',
  'Payment.DemoNotice': 'This is a demo checkout. No real payment is processed.',
  'Payment.Expiry': 'Expiry',
  'Payment.Failed': 'Payment failed. Please try again.',
  'Payment.Processing': 'Processing…',
  'Payment.Title': 'Payment',
  PaymentCardNumber: 'Card Number',
  PaymentShippingEmailPlaceholder: 'Email',
  'Peer.Activity.User.TypingText': 'typing',
  'Peer.Type.User': 'user',
  'PeerInfo.Action.VoiceChat': 'Video Chat',
  'PeerInfo.DeleteChannel': 'Delete Channel',
  'PeerInfo.Discussion': 'Discussion',
  'PeerInfo.SetAboutDescription': 'You can provide an optional description for your group.',
  'PeerInfo.Subscribers': 'Subscribers',
  'PeerMedia.Members': 'Members',
  Phone: 'Phone',
  PhoneCopied: 'Phone copied to clipboard',
  'PhoneNumber.AlreadyTaken': 'This number is already connected to a Telegram account.',
  'PhoneNumber.Change': 'Change Number',
  'PhoneNumber.ChangeHint': 'Please confirm your country code and enter your new phone number.',
  PinFolderLimitReached: 'Sorry, you can\'t pin any more chats to the top.',
  PinnedMessage: 'Pinned Message',
  'PinnedMessage.Hide': 'Hide pinned message',
  'PinnedMessage.Show': 'Show pinned message',
  PinnedMessages: 'Pinned Messages',
  'Pip.ActiveHint': 'To return to the tab, click the button here or the icon in the floating window.',
  'Pip.ActiveTitle': 'Telegram is open in Picture-in-Picture mode',
  'Pip.BackToTab': 'Back to Tab',
  'Pip.Title': 'Picture in Picture',
  'Pip.Unsupported': 'Picture-in-Picture is not supported in this browser.',
  PlaybackRateNormal: 'Normal',
  PleaseEnterFirstPassword: 'Enter a password',
  PleaseReEnterPassword: 'Re-enter your password',
  PleaseWait: 'Please wait...',
  PmReadShowWhen: 'show when',
  Poll: 'Poll',
  PollOptions: 'Poll options',
  'Popup.Attach.AsMedia': 'Send as media',
  'Popup.Attach.EnableSpoilers': 'Hide all with spoilers',
  'Popup.Attach.RemoveSpoilers': 'Remove all spoilers',
  PostStatistics: 'Post Statistics',
  'PostsSearch.TabName': 'Posts',
  'Premium.Boarding.Avatar.Title': 'Animated Profile Pictures',
  'Premium.Boarding.Double.Title': 'Doubled Limits',
  'Premium.Boarding.NoAds.Title': 'No Ads',
  'Premium.Boarding.Stickers.Title': 'Premium Stickers',
  'Premium.Boarding.Title': 'Telegram Premium',
  'Premium.Boarding.Translate.Title': 'Real-Time Translation',
  'Premium.Feature.Avatar.Info': 'Upload a looping video as your profile picture.',
  'Premium.Feature.Badge.Info': 'Show a premium badge next to your name.',
  'Premium.Feature.Badge.Title': 'Premium Badge',
  'Premium.Feature.Chats.Info': 'Change default chat folder, archive and mute new chats.',
  'Premium.Feature.Chats.Title': 'Chat Management',
  'Premium.Feature.Double.Info': 'Up to 1000 channels, 20 folders, 10 pinned chats and 20 public links.',
  'Premium.Feature.Download.Info': 'Download media and files at the maximum speed.',
  'Premium.Feature.Download.Title': 'Faster Downloads',
  'Premium.Feature.Emoji.Info': 'Use unique animated emoji anywhere in chats.',
  'Premium.Feature.Emoji.Title': 'Custom Emoji',
  'Premium.Feature.FileSize.Info': 'Upload files of up to 4 GB each.',
  'Premium.Feature.FileSize.Title': 'Larger Uploads',
  'Premium.Feature.Intro': 'More freedom and dozens of exclusive features with a Telegram Premium subscription.',
  'Premium.Feature.NoAds.Info': 'Get rid of ads in public channels.',
  'Premium.Feature.Reactions.Info': 'React with a vastly expanded set of emoji.',
  'Premium.Feature.Reactions.Title': 'Unique Reactions',
  'Premium.Feature.Status.Info': 'Show a unique animated status next to your name.',
  'Premium.Feature.Status.Title': 'Emoji Status',
  'Premium.Feature.Stickers.Info': 'Unlock exclusive animated stickers.',
  'Premium.Feature.Stories.Info': 'Posting without limits, priority order, stealth mode, saved view history and more.',
  'Premium.Feature.Translate.Caption': 'Watch real-time chat translations with a Telegram Premium subscription.',
  'Premium.Feature.Translate.Info': 'Translate entire chats into your language.',
  'Premium.Feature.Voice.Info': 'Convert voice messages into text.',
  'Premium.Feature.Voice.Title': 'Voice-to-Text',
  'Premium.Manage.Active': 'You have Telegram Premium',
  'Premium.Manage.AutoRenew': 'Auto-Renew',
  'Premium.Manage.AutoRenewOffHint': 'Auto-renew is off. Your Premium subscription will end on the date above.',
  'Premium.Manage.Cancelling': 'Cancelling…',
  'Premium.Manage.ExpiresOn': 'Expires on',
  'Premium.Manage.Hint': 'Your subscription renews automatically. Cancel to stop future charges — Premium stays active until it expires.',
  'Premium.Manage.NoSubscription': 'No active subscription.',
  'Premium.Manage.RenewsOn': 'Renews on',
  'Premium.Row.Active': 'Active — manage subscription',
  'Premium.Row.Subtitle': 'Unlock exclusive features',
  'Premium.SubscribeFor': 'Subscribe for',
  'Premium.Tier.SixMonths': '6 Months',
  PremiumPreviewLastSeen: 'Last Seen Times',
  PremiumPreviewLastSeenDescription: 'View the last seen and read times of others even if you hide yours.',
  PremiumTierAnnual: 'Annual',
  PremiumTierMonthly: 'Monthly',
  'PreviewSender.CaptionPlaceholder': 'Add a caption...',
  'Privacy.AlwaysShareCaption': 'These users will always see this, regardless of the setting above.',
  'Privacy.BioCaption': 'You can restrict who can see the bio on your profile with granular precision.',
  'Privacy.BioRow': 'Who can see my bio?',
  'Privacy.BirthdayChoose': 'Choose who can see your birthday on your profile.',
  'Privacy.BirthdayRow': 'Who can see my birthday?',
  'Privacy.CallsChoose': 'Choose who can call you.',
  'Privacy.ForwardsChoose': 'Choose who can add a link to your account when forwarding your messages.',
  'Privacy.GroupsChoose': 'Choose who can add you to groups and channels.',
  'Privacy.LastSeenCaption': 'You won\'t see Last Seen and Online statuses for people with whom you don\'t share yours. Approximate times will be shown instead (recently, within a week, within a month).',
  'Privacy.LastSeenShortCaption': 'You won’t see Last Seen times for people you don’t share yours with.',
  'Privacy.MessagesCaption': 'Change who can send you messages.',
  'Privacy.MessagesCustomHelp': 'You can restrict who can send you messages with granular precision.',
  'Privacy.NeverShareCaption': 'These users will never see this, regardless of the setting above.',
  'Privacy.Passkey.Create': 'Create Passkey',
  'Privacy.Passkeys': 'Passkeys',
  'Privacy.ProfilePhotoCaption': 'You can restrict who can see your profile photos and videos with granular precision.',
  'Privacy.ProfilePhotoChoose': 'Choose who can see your profile photo.',
  'Privacy.ReadTimeCaption': 'You won\'t see when people read your messages if you don\'t share when you read theirs. This setting does not affect group chats.',
  'Privacy.VoiceCustomHelp': 'You can restrict who can send you voice messages with granular precision.',
  'Privacy.WhoCanSeeThis': 'Who can see this',
  'PrivacyAndSecurity.Item.On': 'On',
  PrivacyDeleteCloudDrafts: 'Delete All Cloud Drafts',
  PrivacyForwardsInfo: 'When forwarded to other chats, messages you send will not link back to your account.',
  PrivacyForwardsTitle: 'Who can add a link to my account when forwarding my messages?',
  PrivacyGroupsTitle: 'Who can add me to group chats?',
  PrivacyLastSeen: 'Last Seen & Online',
  PrivacyMessagesTitle: 'Who can send me messages?',
  'PrivacyModal.Search.Placeholder': 'Add Users or Groups...',
  PrivacyPhone: 'Phone Number',
  PrivacyPhoneInfo: 'Users who have your number saved in their contacts will also see it on Telegram.',
  PrivacyPhoneInfo2: 'Users who add your number will see it only if it is allowed here.',
  PrivacyPhoneInfo3: 'Users who add your number to their contacts will see it on Telegram only if they are your contacts.',
  PrivacyPhoneTitle: 'Who can see my phone number?',
  PrivacyPhoneTitle2: 'Who can find me by my number?',
  PrivacyProfilePhoto: 'Profile Photos',
  PrivacyProfilePhotoTitle: 'Who can see my profile photos?',
  PrivacyReadTime: 'Read Time',
  PrivacyReadTimeTitle: 'Who can see when I read their messages?',
  PrivacySettings: 'Privacy and Security',
  'PrivacySettings.Forwards': 'Forwarded Messages',
  'PrivacySettings.Groups': 'Groups and Channels',
  'PrivacySettings.VoiceCalls': 'Calls',
  'PrivacySettingsController.AddUsers': 'Add Users',
  'PrivacySettingsController.AlwaysAllow': 'Always Allow',
  'PrivacySettingsController.AlwaysShare': 'Always Share With',
  'PrivacySettingsController.Everbody': 'Everybody',
  'PrivacySettingsController.GroupDescription': 'You can restrict who can add you to groups and channels with granular precision.',
  'PrivacySettingsController.MyContacts': 'My Contacts',
  'PrivacySettingsController.NeverAllow': 'Never Allow',
  'PrivacySettingsController.NeverShare': 'Never Share With',
  'PrivacySettingsController.Nobody': 'Nobody',
  'PrivacySettingsController.Paid': 'Paid',
  'PrivacySettingsController.PeerInfo': 'You can add users or entire groups as exceptions that will override the settings above.',
  'PrivacySettingsController.PhoneCallDescription': 'You can restrict who can call you with granular precision.',
  PrivacyTitle: 'Privacy',
  PrivacyVoiceMessages: 'Voice Messages',
  PrivacyVoiceMessagesTitle: 'Who can send me voice or video messages?',
  PrivateChat: 'Private Chat',
  'Profile.ChannelDescription': 'Channel description.',
  'Profile.Info.Channel': 'Channel Info',
  'Profile.Info.Group': 'Group Info',
  'Profile.Info.User': 'User Info',
  'QrLogin.Confirm.Action': 'Confirm',
  'QrLogin.Confirm.Text': 'Confirm the login on the new device',
  'QrLogin.Confirm.Title': 'Log in on a new device?',
  'QRCode.Copied': 'QR Code copied to clipboard',
  'QRCode.CopiedLink': 'Profile link copied to clipboard',
  'QRCode.Copy': 'Copy QR Code',
  'QRCode.Title': 'QR Code',
  Reactions: 'Reactions',
  'Reactions.All.Info': 'Members of this group can use any emoji as reactions to messages.',
  'Reactions.None.Info': 'Members of this group cannot react to messages.',
  'Reactions.Some.Info': 'You can select emoji that will allow members of this group to react to messages.',
  Recent: 'Recent',
  RecentActions: 'Recent Actions',
  'RecentSessions.Error.FreshReset': 'For security reasons, you can\'t terminate older sessions from a device that you\'ve just connected. Please use an earlier connection or wait for a few hours.',
  RecoveryEmail: 'Recovery email',
  RecoveryEmailTitle: 'Recovery Email',
  Remove: 'Remove',
  RemovedUsers: 'Removed Users',
  'RemovedUsers.Description': 'Users removed by group admins cannot rejoin via invite links.',
  Reply: 'Reply',
  ReplyToAnotherChat: 'Reply in Another Chat',
  'Report.DetailsPlaceholder': 'Additional details (optional)',
  'Report.Error': 'Could not send report',
  'Report.Sending': 'Sending…',
  'Report.Sent': 'Report sent',
  ReportBug: 'Report Bug',
  ReportChat: 'Report',
  ReportChatChild: 'Child Abuse',
  ReportChatPornography: 'Pornography',
  ReportChatSpam: 'Spam',
  ReportChatViolence: 'Violence',
  Resend: 'Resend',
  Reset: 'Reset',
  ResetAutomaticMediaDownload: 'Reset Auto-Download Settings',
  ResetAutomaticMediaDownloadAlert: 'Are you sure you want to reset auto-download settings?',
  ResetAutomaticMediaDownloadAlertTitle: 'Reset settings',
  RestartTopic: 'Reopen topic',
  RestrictedUsers: 'Restricted Users',
  'RestrictedUsers.Description': 'These members have limited rights in this group.',
  RevokeAlert: 'Are you sure you want to revoke this link? Once the link is revoked, no one will be able to join using it.',
  RevokeButton: 'Revoke',
  RevokeLink: 'Revoke Link',
  RevokedLinks: 'Revoked Links',
  'Rtmp.MediaViewer.Live': 'LIVE',
  'Rtmp.OutputPopup.Title': 'Output Device',
  'Rtmp.StreamPopup.Description': 'To stream video with another app, enter this Server URL and Stream Key in your streaming app. Software encoding recommended (x264 in OBS).',
  'Rtmp.StreamPopup.EndLiveStream': 'END LIVE STREAM',
  'Rtmp.StreamPopup.Hint': 'Once you start broadcasting in your streaming app, click Start Streaming below.',
  'Rtmp.StreamPopup.KeyCopied': 'Key copied to clipboard',
  'Rtmp.StreamPopup.RevokeStreamKey': 'Revoke Stream Key',
  'Rtmp.StreamPopup.ServerURL': 'Server URL',
  'Rtmp.StreamPopup.StartStreaming': 'START STREAMING',
  'Rtmp.StreamPopup.StreamKey': 'Stream Key',
  'Rtmp.StreamPopup.Title': 'Stream With...',
  'Rtmp.StreamPopup.TitleSettings': 'Stream Settings',
  'Rtmp.StreamPopup.URLCopied': 'URL copied to clipboard',
  'Rtmp.Watching': {
    other_value: '%s watching',
  },
  'Rtmp.Topbar.Join': 'Join',
  'Rtmp.Topbar.NoViewers': 'No viewers',
  'Rtmp.Topbar.Title': 'Live Stream',
  Save: 'Save',
  Saved: 'Saved',
  SavedGifsLimitTitle: 'Saved GIFs',
  SavedMessages: 'Saved Messages',
  'SavedTag.NamePlaceholder': 'Add a tag name',
  'SavedTag.Rename': 'Rename tag',
  'SavedTag.Tags': 'Tags',
  SavedTagFilterByTag: 'Filter by Tag',
  'Schedule.ScheduledFor': 'Scheduled for',
  'Schedule.SendOn': 'Send on',
  'Schedule.SendTodayAt': 'Send today at',
  'Schedule.SendWhenOnline': 'Send When Online',
  'ScheduleController.at': 'at',
  ScheduledMessages: 'Scheduled Messages',
  Search: 'Search',
  'Search.Comments': 'Search comments',
  'Search.Confirm.ClearHistory': 'Are you sure you want to clear your search history?',
  'Search.Empty.FromPrefix': 'There were no messages from',
  'Search.Empty.QueryPrefix': 'There were no results for',
  'Search.Empty.Suffix': '. Try a new search.',
  'Search.EmptyQuery': 'Try searching.',
  'Search.From': 'From:',
  'Search.Hashtag': 'Search Hashtag',
  'Search.HelpHashtag': 'Enter a hashtag to find messages containing it.',
  'Search.Member': 'Search Members',
  'Search.MyChannels': 'My Channels',
  SearchEmoji: 'Search Emoji',
  SearchEmptyViewTitle: 'No Results',
  SearchGIFs: 'Search GIFs',
  SearchMessages: 'Messages',
  'SecretChat.Accept': 'Accept',
  'SecretChat.Awaiting': 'Waiting for the other party to accept the secret chat…',
  'SecretChat.EncryptionKey': 'Encryption Key',
  'SecretChat.Invitation': 'Secret chat invitation',
  'SecretChat.KeyNotReady': 'The encryption key has not been agreed yet.',
  'SecretChat.KeyVerification.Hint': 'Compare these emoji with the ones your contact sees on their device. If they match, the chat is end-to-end encrypted.',
  'SecretChat.Reject': 'Decline',
  'SecretChat.Rejected': 'Secret chat rejected',
  'SecretChat.New': 'New Secret Chat',
  Send: 'Send',
  SendAsFile: 'Send as file',
  SendMessage: 'Send Message',
  'Separator.ShowMore': 'show more',
  SessionsInfo: 'Manage your sessions on all your devices.',
  SessionsListInfo: 'The official Telegram app is available for Android, iPhone, iPad, Windows, macOS and Linux.',
  SessionsTitle: 'Active Sessions',
  SetColor: 'Set a color',
  SetUrlPlaceholder: 'Link',
  Settings: 'Settings',
  'Settings.BigEmoji': 'Big Emoji',
  'Settings.Limits': 'Limits',
  'Settings.Security': 'Security',
  Share: 'Share',
  'ShareModal.Search.ForwardPlaceholder': 'Forward to...',
  ShareWith: 'Share with',
  SharedFilesTab2: 'Files',
  'SharedFolder.Link.Title': 'Add Folder',
  'SharedFolder.Edit.Title': 'Share Folder',
  'SharedFolder.Link.Caption': 'Create an invite link so others can join the group chats in this folder.',
  SharedLinksTab2: 'Links',
  'SharedMedia.Audio': 'Audio',
  'SharedMedia.Empty': 'Nothing here yet.',
  'SharedMedia.Gifts': 'Gifts',
  'SharedMedia.Gifts.Empty': 'No gifts yet',
  SharedMediaTab2: 'Media',
  SharedMusicTab2: 'Music',
  SharedVoiceTab2: 'Voice',
  ShowTranslateButton: 'Show Translate Button',
  ShowTranslateChatButton: 'Translate Entire Chats',
  'Sidebar.Resize.ShiftTip': 'Hold **Shift** to resize both columns at once',
  SimilarChannels: 'Similar Channels',
  Slowmode: 'Slow Mode',
  SlowmodeInfo: 'Choose how often members of the group are able to send messages.',
  SomeReactions: 'Some reactions',
  'StarGift.ConvertTo': 'Convert to',
  'StarGift.Converted': 'Gift converted',
  'StarGift.GiftTo': 'Gift to',
  'StarGift.HiddenFromProfile': 'Hidden from your profile',
  'StarGift.HideFromProfile': 'Hide from Profile',
  'StarGift.MessagePlaceholder': 'Message (optional)',
  'StarGift.SendFor': 'Send for',
  'StarGift.Sent': 'Gift Sent',
  'StarGift.ShowInProfile': 'Show in Profile',
  'StarGift.ShowMyName': 'Show my name',
  'StarGift.View': 'View Gift',
  StarGiftFromShort: 'From',
  StarGiftHideMyName: 'Hide My Name',
  StarGiftSellTitleStars: 'Price in Stars',
  StarGiftShowLimited: 'Limited',
  StarGiftSoldOutBadge: 'sold out',
  StarGiftTitle: 'Gift',
  'Stars.Balance': 'Your balance',
  'Stars.DemoNotice': 'Demo: top-up adds Stars instantly, no real payment.',
  'Stars.NotEnough': 'Not enough Stars — top up to continue.',
  'Stars.RecentTransactions': 'Recent Transactions',
  'Stars.Subscription': 'Subscription',
  'Stars.Subscription.Cancel': 'Cancel Subscription',
  'Stars.Subscriptions.PerMonth': 'per month',
  'Stars.TopUpAction': 'Top up Stars',
  'Stars.TopUpTitle': 'Top-Up',
  'Stars.Transaction': 'Transaction',
  'Stars.Wallet': 'Wallet',
  StarsFailed: 'Failed',
  'StarsReaction.Caption': 'Choose how many Stars you want to send to support this message.',
  'StarsReaction.Title': 'React with Stars',
  StarsReactionTitle: 'Star Reaction',
  StarsReactionTopSenders: 'Top Senders',
  StarsTransactionsIncoming: 'Incoming',
  StarsTransactionsOutgoing: 'Outgoing',
  StartMessaging: 'Start Messaging',
  StatisticOverview: 'Overview',
  StatisticViews: 'Views',
  Statistics: 'Statistics',
  'Statistics.Forwards': 'Forwards',
  'Statistics.Loading': 'Loading statistics…',
  'Statistics.MediaPost': 'Media post',
  'Statistics.MemberGrowth': 'Member growth',
  'Statistics.PostsByDay': 'Posts by day',
  'Statistics.SubscriberGrowth': 'Subscriber growth',
  'Statistics.TopPosts': 'Top posts',
  'Statistics.TotalViews': 'Total views',
  'Statistics.Unavailable': 'Statistics are not available.',
  'Statistics.ViewsByDay': 'Views by day',
  Stickers: {
    one_value: '%1$d sticker',
    other_value: '%1$d stickers',
  },
  'Stickers.AddSets': 'Add Sticker Sets',
  'Stickers.ClearRecent.Text': 'Are you sure you want to clear your recent stickers?',
  'Stickers.MySets': 'My Sticker Sets',
  'Stickers.NoSets': 'No sticker sets installed',
  'Stickers.RemoveFromFavorites': 'Remove from Favorites',
  'Stickers.SearchAdded': 'Added',
  'Stickers.SearchSets': 'Search sticker sets',
  'Stickers.SuggestStickers': 'Suggest Stickers by Emoji',
  StickersName: 'Stickers and Emoji',
  'StickersTab.SearchPlaceholder': 'Search Stickers',
  'StorageQuota.CacheSizeLimit': 'Cache size limit',
  'StorageQuota.CacheSizeLimitAuto': 'Auto',
  'StorageQuota.CachedFiles': 'Cached files',
  'StorageQuota.Caption': 'Note that cache required for the app to function properly will not be cleared.',
  'StorageQuota.ClearAll': 'Clear All',
  'StorageQuota.ClearAllConfirmation': 'Are you sure you want to clear all cached data?',
  'StorageQuota.ClearCacheOlderThan': 'Clear cache older than',
  'StorageQuota.ClearCachedFiles': 'Clear cached files',
  'StorageQuota.ClearConfirmation': 'Are you sure you want to clear %s of cached data?',
  'StorageQuota.ClearConfirmationUnknown': 'Are you sure you want to clear the cached data?',
  'StorageQuota.Images': 'Images',
  'StorageQuota.StickersEmoji': 'Stickers and emojis',
  'StorageQuota.Title': 'Estimated storage quota',
  'StorageQuota.VideoFiles': 'Video files',
  Stories: 'Stories',
  'Stories.StealthMode.Activated.Title': 'Stealth Mode On',
  'Stories.StealthMode.Button': 'ENABLE STEALTH MODE',
  'Stories.StealthMode.Cooldown': 'Available in %s',
  'Stories.StealthMode.Cooldown.Title': 'Stealth Mode is on a cooldown',
  'Stories.StealthMode.Row1.Subtitle': 'Hide my views from the past **%s**.',
  'Stories.StealthMode.Row1.Title': 'Hide Recent Views',
  'Stories.StealthMode.Row2.Subtitle': 'Hide my views for the next **%s**.',
  'Stories.StealthMode.Row2.Title': 'Hide Upcoming Views',
  'Stories.StealthMode.Subtitle': 'Turn Stealth Mode on to watch without appearing in the list of viewers.',
  'Stories.StealthMode.Title': 'Stealth Mode',
  'Stories.StealthMode.Unavailable': 'Stealth Mode is unavailable',
  'Stories.StealthMode.View': 'Hide My View',
  'Story.AddToProfile': 'Post to Profile',
  'Story.Edit': 'Edit story',
  'Story.Edited': 'Story edited',
  'Story.React': 'React',
  'Story.RemoveFromProfile': 'Remove from Profile',
  'Story.Repost': 'Repost',
  'Story.Time.HoursAgo': 'h ago',
  'Story.Time.MinutesAgo': 'min ago',
  'Story.Viewers': 'Viewers',
  StoryJustNow: 'just now',
  StoryStatistics: 'Story Statistics',
  SubscribeRequests: 'Join Requests',
  Subscribers: {
    one_value: '%1$d subscriber',
    other_value: '%1$d subscribers',
  },
  'SuggestedPosts.Empty': 'No suggested posts here yet…',
  'SuggestedPosts.PostPlaceholder': 'Type your post…',
  'SuggestedPosts.Publish': 'Publish',
  'SuggestedPosts.PublishingTime.Hint': 'Leave empty to publish anytime.',
  'SuggestedPosts.PublishingTime.Label': 'Publishing Time',
  'SuggestedPosts.Reject': 'Reject',
  'SuggestedPosts.Schedule': 'Schedule',
  'SuggestedPosts.Status.Approved': 'Approved',
  'SuggestedPosts.Status.OnReview': 'On review',
  'SuggestedPosts.Status.Rejected': 'Rejected',
  'SuggestedPosts.Submit': 'Suggest',
  'SuggestedPosts.SuggestAPost': 'Suggest a post',
  'SuggestedPosts.Title': 'Suggested Posts',
  'SuggestedPosts.YourPost': 'Your post',
  'SuggestedPosts.YourSuggestions': 'Your suggestions',
  'Suggestion.Notifications.Dismissed': 'You can turn notifications back on in the settings.',
  'Suggestion.Notifications.Subtitle': 'Enable notifications to stay updated.',
  'Suggestion.Notifications.Title': 'Never miss a message! 🔔',
  'Telegram.GeneralSettingsViewController': 'General Settings',
  'Telegram.LanguageViewController': 'Language',
  TelegramFeatures: 'Telegram Features',
  TelegramStars: 'Telegram Stars',
  Terminate: 'Terminate',
  TerminateAllSessions: 'Terminate All Other Sessions',
  TerminateSessionText: 'Are you sure you want to terminate this session?',
  'Text.Context.Copy.Email': 'Copy Email',
  'Text.Context.Copy.Hashtag': 'Copy Hashtag',
  'Text.Context.Copy.Username': 'Copy Username',
  TextSize: 'Message Text Size',
  'Theme.Light': 'Light',
  'Theme.System': 'System',
  'Theme.Tinted': 'Tinted',
  ThemeLight: 'Day',
  ThemeNight: 'Night',
  Topics: 'Topics',
  TopicsCount: {
    one_value: '%d topic',
    other_value: '%d topics',
  },
  TranscribeHide: 'Hide Transcription',
  TranscribeUnavailable: 'Transcription unavailable in demo mode',
  TranscribeVoice: 'Transcribe Voice Message',
  Translate: 'Translate',
  'Translate.Failed': 'Translation failed',
  'Translate.FromLanguage': 'From language',
  'Translate.SectionCaption': 'Show a Translate button in the message menu to translate messages into your language.',
  'Translate.SectionTitle': 'Message Translation',
  'Translate.ToLanguage': 'To language',
  Translation: 'Translation',
  TurnPasswordOffQuestion: 'Are you sure you want to disable your password?',
  TurnPasswordOffQuestionTitle: 'Disable password',
  'TwoStepAuth.ChangeEmail': 'Change Recovery Email',
  'TwoStepAuth.ChangePassword': 'Change Password',
  'TwoStepAuth.ConfirmPassword': 'Please confirm your password.',
  'TwoStepAuth.CreateCaption': 'Create a password to protect your account.',
  'TwoStepAuth.EmailHelp': 'Add a recovery email to restore access if you forget your password.',
  'TwoStepAuth.EnterCurrentPassword': 'Please enter your current password',
  'TwoStepAuth.GenericHelp': 'You have enabled Two-Step verification.\nYou\'ll need the password you set up here to log in to your Telegram account.',
  'TwoStepAuth.HintCaption': 'You can create an optional hint for your password.',
  'TwoStepAuth.InvalidPassword': 'Invalid password',
  'TwoStepAuth.PasswordHelp': 'This password will be required when you log in on a new device in addition to the code you get via SMS.',
  'TwoStepAuth.PasswordsDontMatch': 'Passwords don’t match.',
  'TwoStepAuth.ReEnterPassword': 'Re-enter Password',
  'TwoStepAuth.RecoveryEmailPlaceholder': 'Recovery email (optional)',
  'TwoStepAuth.RemovePassword': 'Disable Password',
  'TwoStepAuth.SetPassword': 'Set a Password',
  'TwoStepAuth.SetPasswordCaption': 'Set an additional password that will be required when you log in on a new device.',
  'TwoStepAuth.SetPasswordHelp': 'You can set a password that will be required when you log in on a new device in addition to the code you get in the SMS.',
  'TwoStepAuth.SetupEmail': 'Set Recovery Email',
  'TwoStepAuth.SetupHintPlaceholder': 'Hint',
  'TwoStepAuth.SetupHintTitle': 'Password Hint',
  TwoStepVerification: 'Two-Step Verification',
  TwoStepVerificationPasswordReturnSettings: 'Return to Settings',
  TwoStepVerificationPasswordSet: 'Password Set!',
  TwoStepVerificationSetPassword: 'Set Password',
  TypePrivate: 'Private',
  TypePublic: 'Public',
  Unarchive: 'Unarchive',
  Unban: 'Unban',
  Unblock: 'Unblock',
  UnblockUser: 'Unblock user',
  Undo: 'Undo',
  'Unit.Bytes': 'B',
  'Unit.Days.Short': 'd',
  'Unit.Gigabytes': 'GB',
  'Unit.Hours.Short': 'h',
  'Unit.Kilobytes': 'KB',
  'Unit.Megabytes': 'MB',
  'Unit.Minutes.Abbr': 'min',
  'Unit.Minutes.Short': 'm',
  'Unit.Months.Abbr': 'mo',
  'Unit.Seconds.Short': 's',
  UnpinMessage: 'Unpin',
  UnreadMessages: 'Unread Messages',
  Updating: 'Updating...',
  UserBio: 'Bio',
  'UserInfo.SetPhotoTitle': 'Set Photo',
  'UserPermissions.Duration': 'Duration',
  'UserPermissions.Duration.Forever': 'Forever',
  'UserRestrictions.Action': 'Restrict',
  'UserRestrictions.CanDoMember': 'What can this member do?',
  'UserRestrictions.Title': 'Restrict Member',
  UserRestrictionsBlock: 'Ban and remove from group',
  UserRestrictionsChangeInfo: 'Change Chat Info',
  UserRestrictionsInviteUsers: 'Add Users',
  UserRestrictionsPinMessages: 'Pin Messages',
  UserRestrictionsSend: 'Send Messages',
  UserRestrictionsSendMedia: 'Send Media',
  Username: 'Username',
  UsernameCopied: 'Username copied to clipboard.',
  VideoCall: 'Video Call',
  'VoiceChat.Status.Members': {
    one_value: '%d participant',
    other_value: '%d participants',
  },
  VoipUnmute: 'Unmute',
  ViewDiscussion: 'View discussion',
  ViewsPerPost: 'Views Per Post',
  'VoiceChat.Leave': 'Leave',
  'VoiceChat.Status.Listening': 'listening',
  'VoiceChat.Status.Muted': 'muted',
  'VoiceChat.Status.You': 'This is you',
  'WebApp.CameraDenied': 'Camera access denied',
  'WebApp.CloseConfirm': 'Close this Mini App?',
  'WebApp.DataSent': 'Data sent',
  'WebApp.PayConfirm': 'Pay this invoice?',
  'WebApp.PhoneRequest': 'Share your phone number with this bot?',
  'WebApp.QrUnsupported': 'QR scanning is not supported in this browser',
  'WebApp.WriteAccess.Question': 'Allow this bot to message you?',
  'WebPage.InstantView': 'INSTANT VIEW',
  Weeks: {
    one_value: '%1$d week',
    other_value: '%1$d weeks',
  },
  WhoCanCallMe: 'Who can call me?',
  Years: {
    one_value: '%1$d year',
    other_value: '%1$d years',
  },
  YourEmailSkip: 'Skip',
  YourName: 'Your Name',
}

export default lang

/** Значение строки: обычная или с формами числа. */
export type LangPackValue = string | { one_value?: string; few_value?: string; many_value?: string; other_value?: string }

/** Символический ключ строки — как `keyof typeof lang` у tweb (`lib/langPack.ts:70`). */
export type LangPackKey = keyof typeof lang

