// Английский источник строк — как у tweb (`tweb/src/lang.ts`): ключ символический,
// значение — английский текст. Ключи, совпавшие с оригиналом дословно, взяты у оригинала
// вместе с его текстом; остальные названы по его правилам (`Раздел.Подраздел.Смысл`).
// Значение-объект — форма числа (`langPackStringPluralized`), форму выбирает `I18n.format`.
//
// ЭТОТ ФАЙЛ — НИЖНИЙ СЛОЙ ВСЕЙ ЛОКАЛИЗАЦИИ, а не запасной: `I18n.applyServerLangPack`
// кладёт его ПОД серверный пакет любого языка (`lib/langPack.ts`), поэтому ключ,
// которого нет в переводе, читается по-английски, а не своим именем. Он же — исходник
// для сервера: `backend/internal/langsource` снимает с него таблицу английского вместе
// с `src/i18n/dict.*.ts`.
const lang = {
  'ALongTimeAgo': 'last seen a long time ago',
  'AccDescr.MicrophoneLevel': 'Microphone level',
  'AccDescr.PlaybackSpeed': 'Playback speed',
  AccDescrEditing: 'Editing',
  'AccountSettings.Filters': 'Chat Folders',
  'AccountSettings.Language': 'Language',
  'AccountSettings.Notifications': 'Notifications and Sounds',
  'AccountSettings.PrivacyAndSecurity': 'Privacy and Security',
  'AccountSettings.SpeakersAndCamera': 'Speakers and Camera',
  Add: 'Add',
  AddContact: 'Add to contacts',
  AddContactTitle: 'Add Contact',
  AddFactCheck: 'Add Fact Check',
  AddMembersAlertCountText: 'Are you sure you want to add %1$s to **%2$s**?',
  AddMembersAlertNamesText: 'Are you sure you want to add %1$s to **%2$s**?',
  AddMembersAlertTitle: 'Add %1$s',
  AddOneMemberAlertTitle: 'Add member',
  AddToChannel: 'Add to Channel',
  AddToFavorites: 'Add to Favorites',
  AddToGroup: 'Add to Group',
  'AdminRights.ManageMessages': 'Manage Messages',
  Administrators: 'Administrators',
  'Alert.Confirm.Discard': 'Discard',
  'Alert.UserDoesntExists': 'Sorry, this user doesn\'t seem to exist.',
  AlertClearHistory: 'Clear History',
  AllChats: 'All Chats',
  AllReactions: 'All reactions',
  AndOther: { one_value: 'and %1$d other', other_value: 'and %1$d others' },
  AppName: 'Telegram',
  'Appearance.Color.Hex': 'HEX',
  'Appearance.Color.RGB': 'RGB',
  'Appearance.Reset': 'Reset to Defaults',
  ApproveNewMembers: 'Request Admin Approval',
  ApproveNewMembersDescription: 'Turn this on if you want users to join only after they are approved by an admin.',
  Archive: 'Archive',
  'Archive.Empty': 'No archived chats',
  ArchivedChats: 'Archived Chats',
  AreYouSureBlockContact2: 'Are you sure you want to block **%1$s**?',
  AreYouSureClearDrafts: 'Are you sure you want to delete all cloud drafts?',
  AreYouSureClearDraftsTitle: 'Delete cloud drafts',
  AreYouSureClearHistory: 'Are you sure you want to delete all messages in this chat?',
  AreYouSureClearHistorySavedMessages: 'Are you sure you want to clear **Saved Messages**?',
  AreYouSureClearHistoryWithChannel: 'Are you sure you want to clear the channel history in **%1$s**?',
  AreYouSureClearHistoryWithUser: 'Are you sure you want to clear your chat history with **%1$s**?',
  AreYouSureDeleteAndExit: 'Are you sure you want to delete and leave the group?',
  AreYouSureDeleteAndExitChannel: 'Do you want to delete and leave the channel?',
  AreYouSureDeleteAndExitName: 'Are you sure you want to delete and leave the group **%1$s**?',
  AreYouSureDeleteContact: 'Are you sure you want to delete this contact?',
  AreYouSureDeleteFewMessages: 'Are you sure you want to delete these messages?',
  AreYouSureDeleteFewMessagesBot: 'Do you want to delete these messages?\nThis will delete them just for you.',
  AreYouSureDeleteFewMessagesMega: 'Are you sure you want to delete these messages for everyone?',
  AreYouSureDeleteSingleMessage: 'Are you sure you want to delete this message?',
  AreYouSureDeleteSingleMessageBot: 'Do you want to delete this message?\nThis will delete it just for you.',
  AreYouSureDeleteSingleMessageMega: 'Are you sure you want to delete this message for everyone?',
  AreYouSureDeleteThisChatWithUser: 'Are you sure you want to delete the chat with **%1$s**?',
  AreYouSureSessionTitle: 'Terminate session',
  AreYouSureSessions: 'Are you sure you want to terminate all other sessions?',
  AreYouSureSessionsTitle: 'Terminate sessions',
  AskAQuestion: 'Ask a Question',
  AttachAlbum: 'Album',
  AttachAudio: 'Voice message',
  AttachContact: 'Contact',
  AttachGif: 'GIF',
  AttachLiveLocation: 'Live Location',
  AttachLocation: 'Location',
  AttachPhoto: 'Photo',
  AttachRound: 'Video message',
  AttachSticker: 'Sticker',
  AttachVideo: 'Video',
  AudioUnknownArtist: 'Unknown artist',
  'AuthSessions.IncompleteAttempts': 'Incomplete login attempts',
  'AuthSessions.IncompleteAttemptsInfo': 'These devices have no access to your account. The code was entered correctly, but no correct password was given.',
  'AuthSessions.View.Application': 'Application',
  'AuthSessions.View.Device': 'Device',
  'AuthSessions.View.Location': 'Location',
  'AuthSessions.View.LocationInfo': 'This location estimate is based on the IP address and may not always be accurate.',
  'AuthSessions.View.System': 'System version',
  'AuthSessions.View.TerminateSession': 'Terminate Session',
  AuthorHiddenShort: 'Anonymous',
  AutoDeleteMessages: 'Auto-delete messages',
  'AutoDeleteMessages.Disable': 'Disable',
  'AutoDeleteMessages.InfoChannel': 'Automatically delete messages for everyone in this channel after a certain amount of time.',
  'AutoDeleteMessages.InfoChat': 'Automatically delete messages for everyone in this chat after a certain amount of time.',
  'AutoDeleteMessages.InfoDefault': 'Automatically delete messages for everyone in chats you start after a certain amount of time.',
  'AutoDeleteMessages.SectionCaption': 'If enabled, all new messages in chats you start will be automatically deleted for everyone at some point after they have been sent. This will not affect your existing chats.',
  'AutoDeleteMessages.SectionTitle': 'Self-destruct timer',
  'AutoDeleteMessages.SetOtherTime': 'Set other time',
  AutoDeleteMessagesShort: 'Auto-delete',
  AutoDownloadAudioInfo: 'Voice messages are tiny, so they\'re always downloaded automatically.',
  AutoDownloadChannels: 'Channels',
  AutoDownloadContacts: 'Contacts',
  AutoDownloadFiles: 'Files',
  AutoDownloadFilesTitle: 'Auto-download files and music',
  AutoDownloadGroups: 'Groups',
  AutoDownloadLargeFilesInfo: 'Larger files are never downloaded automatically.',
  AutoDownloadMaxFileSize: 'Maximum file size',
  AutoDownloadMaxVideoSize: 'Max video size',
  AutoDownloadMedia: 'Auto-Download Media',
  AutoDownloadMobile: 'When using mobile data',
  AutoDownloadOff: 'Off',
  AutoDownloadOnAllChats: 'On in all chats',
  AutoDownloadOnFor: 'On for %1$s',
  AutoDownloadOnUpToFor: 'Up to %1$s for %2$s',
  AutoDownloadPhotos: 'Photos',
  AutoDownloadPhotosTitle: 'Auto-download photos',
  AutoDownloadPm: 'PM',
  AutoDownloadRoaming: 'When roaming',
  // Разделители перечисления — их берёт `join()` (`lib/langPack.ts`, порт tweb :687).
  // Взяты у оригинала дословно (tweb `lang.ts:3394-3395`) вместе с именами: в оригинале
  // они тоже названы по разделу автозагрузки, откуда пришли первым потребителем.
  'AutoDownloadSettings.Delimeter': ', ',
  'AutoDownloadSettings.LastDelimeter': ' and ',
  AutoDownloadUpToOnAllChats: 'Up to %1$s in all chats',
  AutoDownloadVideos: 'Videos',
  AutoDownloadVideosTitle: 'Auto-download videos and GIFs',
  AutoDownloadWifi: 'When connected to Wi-Fi',
  AutoNightSystemDefault: 'System Default',
  AutodownloadChannels: 'Channels',
  AutodownloadContacts: 'Contacts',
  AutodownloadGroupChats: 'Group Chats',
  AutodownloadPrivateChats: 'Private Chats',
  AutodownloadSizeLimitUpTo: 'up to %1$s',
  AutomaticMediaDownload: 'Automatic media download',
  AvailableReactions: 'Available reactions',
  'Bio.Description': 'Any details such as age, occupation or city.\nExample: 23 y.o. designer from San Francisco',
  BioCopied: 'Bio copied to clipboard.',
  Birthday: 'Birthday',
  'Birthday.PrivacyHint': 'In settings you can choose who will see your birthday.',
  BirthdaySuggestIncoming: '%s suggested you add your birthday',
  BirthdaySuggestOutgoing: 'You suggested %s to add a birthday',
  'BlockModal.Search.Placeholder': 'Block user...',
  BlockUser: 'Block user',
  BlockedEmpty: 'None',
  BlockedUsers: 'Blocked Users',
  BlockedUsersInfo: 'Blocked users can\'t send you messages or add you to groups. They will not see your profile photos, stories, online and last seen status.',
  BlockedUsersInfoShort: 'Blocked users can\'t send you messages or see your profile.',
  'Boost.AlreadyBoosting': 'You are boosting this channel.',
  'Boost.Boosted': 'You boosted this channel',
  'Boost.Error.NoSlot': 'Could not boost. You need Telegram Premium and a free boost slot.',
  'Boost.Subtitle': 'Help boost this channel to unlock new features.',
  BoostChannel: 'Boost Channel',
  BoostingGiveaway: 'Giveaway',
  BoostingGiveawayDeleteMsgText: 'Deleting this message won\'t cancel the giveaway — the winners will still be selected on **%s**.\n\nOnce deleted, the Giveaway Announcement cannot be restored.',
  BoostingGiveawayDeleteMsgTitle: 'Delete announcement',
  BoostingGiveawayEnd: 'Giveaway ended',
  BoostingGiveawayPrizes: '**Giveaway Prizes**',
  BoostingStartGiveawayConfirmTitle: 'Start Giveaway',
  BoostingWinnersDate: '**Winners Selection Date**',
  BoostsLevel2: 'Level',
  'BoostsViaGifts.Duration': 'Duration of premium subscriptions',
  'BoostsViaGifts.End': 'Date when giveaway ends',
  'BoostsViaGifts.Quantity': 'Quantity of prizes',
  Bot: 'bot',
  BotStart: 'START',
  BuyStars: 'Buy Stars',
  'Calendar.ClearHistory': 'Clear History',
  'Calendar.Next': 'Next',
  'Calendar.Previous': 'Previous',
  Call: 'Call',
  'Call.Accept': 'Accept',
  'Call.CameraOff': 'Turn off camera',
  'Call.CameraOn': 'Turn on camera',
  'Call.Decline': 'Decline',
  'Call.EncryptionKey': 'Encryption key',
  'Call.EncryptionKeyHint': 'If the emoji match on both devices, this call is end-to-end verified.',
  'Call.Input': 'Input',
  'Call.MicrophoneOff': 'Microphone is off',
  'Call.Mute': 'Mute',
  'Call.Output': 'Output',
  'Call.PrivacyError': 'This user doesn\'t accept calls',
  'Call.ShareScreen': 'Share screen',
  'Call.StatusBusy': 'Busy',
  'Call.StatusConnecting': 'Connecting...',
  'Call.StatusDeclined': 'Declined',
  'Call.StatusEnded': 'Call Ended',
  'Call.StatusNoAnswer': 'No answer',
  'Call.StatusRinging': 'Ringing...',
  'Call.StopScreenSharing': 'Stop screen sharing',
  'Call.VideoToggle': 'video',
  CallBack: 'Call Back',
  CallMessageIncoming: 'Incoming Call',
  CallMessageIncomingDeclined: 'Declined Call',
  CallMessageIncomingMissed: 'Missed Call',
  CallMessageOutgoing: 'Outgoing Call',
  CallMessageOutgoingMissed: 'Cancelled Call',
  CallMessageVideoIncoming: 'Incoming Video Call',
  CallMessageVideoIncomingDeclined: 'Declined Video Call',
  CallMessageVideoIncomingMissed: 'Missed Video Call',
  CallMessageVideoOutgoing: 'Outgoing Video Call',
  CallMessageVideoOutgoingMissed: 'Cancelled Video Call',
  'CallSettings.Camera': 'Device',
  'CallSettings.CameraSection': 'Camera',
  'CallSettings.CameraUnavailable': 'Camera is unavailable. Check camera access and try again.',
  'CallSettings.DeviceDefault': 'Default',
  'CallSettings.EndCall': 'End Call',
  'CallSettings.InputDevice': 'Input device',
  'CallSettings.InputSection': 'Microphone',
  'CallSettings.Microphone': 'Microphone',
  'CallSettings.MicrophoneUnavailable': 'Microphone is unavailable. Check microphone access and try again.',
  'CallSettings.OutputDevice': 'Output device',
  'CallSettings.OutputSection': 'Speakers',
  'CallSettings.Speakers': 'Speakers',
  Calls: 'Calls',
  'Calls.Status.Group': '(%1$s) %2$s',
  // «Сколько ещё человек может вступить по ссылке» — ключ ОРИГИНАЛА (tweb lang.ts:2316,
  // `chatInviteLinks.tsx:452`) с числом ВНУТРИ строки. Наш `InviteLinks.CanJoinSuffix`
  // («can join») был выдуман и склеивался с числом в коде: суффикс печатался префиксом,
  // и по-русски выходило «могут вступить 5».
  CanJoin: {
    other_value: '%1$d can join',
  },
  Cancel: 'Cancel',
  Channel: 'Channel',
  'Channel.Admin.Dismiss': 'Dismiss Admin',
  'Channel.DescriptionHolderDescrpiton': 'You can provide an optional description for your channel.',
  'Channel.DescriptionPrefix': 'You can provide an optional description for your',
  'Channel.EditAdmin.PermissionInviteSubscribers': 'Add Subscribers',
  'Channel.Persmission.MessageBlock': 'Text is not Allowed',
  'Channel.UsernameAboutChannel': 'People can share this link with others and can find your channel using Telegram search.',
  'Channel.UsernameAboutGroup': 'People can share this link with others and find your group using Telegram search.',
  ChannelAddAdmin: 'Add Admin',
  ChannelAddException: 'Add Exception',
  ChannelAddSubscribers: 'Add Subscribers',
  ChannelBroadcast: 'Broadcast',
  ChannelCreator: 'Owner',
  ChannelDelete: 'Delete Channel',
  ChannelDeleteMenu: 'Delete channel',
  'ChannelDirectMessages.Settings.Title': 'Direct Messages',
  ChannelJoin: 'JOIN',
  ChannelLeaveAlertWithName: 'Are you sure you want to leave **%1$s**?',
  ChannelLinkInfo: 'Anyone who has Telegram installed will be able to join your channel by following this link.',
  ChannelPermissions: 'Permissions',
  ChannelPermissionsHeader: 'What can members of this group do?',
  ChannelPrivate: 'Private Channel',
  ChannelPrivateInfo: 'Private channels can only be joined via an invite link.',
  ChannelPrivateLinkHelp: 'People can join your channel by following this link. You can revoke the link any time.',
  ChannelPublic: 'Public Channel',
  ChannelPublicInfo: 'Public channels can be found in search, anyone can join them.',
  ChannelSettingsJoinRequest: 'Approve new members',
  ChannelSignMessages: 'Sign Messages',
  ChannelSignMessagesInfo: 'Add names of admins to the messages they post',
  ChannelSignMessagesWithProfile: 'Show Authors\' Profiles',
  ChannelSignProfilesInfo: 'Add names and photos of admins to the messages they post, linking to their profiles.',
  ChannelType: 'Channel Type',
  'ChannelVisibility.Confirm.MakePrivate.Channel': 'If you make this channel private, the name @%@ will be removed. Anyone else will be able to take it for their public groups or channels.',
  'ChannelVisibility.Confirm.MakePrivate.Group': 'If you make this group private, the name @%@ will be removed. Anyone else will be able to take it for their public groups or channels.',
  Channels: { one_value: '%1$d channel', other_value: '%1$d channels' },
  ChannelsOnly: 'Channels',
  ChannelsTab: 'Channels',
  'Chat.Accessory.Edit': 'Edit message',
  // Плашка пересылки в композере. Обе надписи — ФОРМЫ ЧИСЛА со счётчиком внутри,
  // 1:1 с оригиналом (tweb lang.ts:3430 и :3436), и зовут их с числом там же, где
  // оригинал: `components/composer/ReplyWrapper.tsx` — порт `input.ts:736, 4517`.
  'Chat.Accessory.Forward': { one_value: 'Forward Message', other_value: 'Forward %d Messages' },
  'Chat.Accessory.Forward.From': 'From',
  'Chat.Accessory.Forward.You': 'You',
  'Chat.Accessory.Hidden': {
    one_value: 'Forward Message (sender\'s name hidden)',
    other_value: 'Forward %d Messages (senders\' names hidden)',
  },
  'Chat.Accessory.Reply': 'Reply to',
  'Chat.Alert.Forward.Action.Another': 'Forward to Another Chat',
  'Chat.Alert.Forward.HideCaption': 'Hide caption',
  'Chat.Alert.Forward.HideSenderName': 'Hide sender name',
  'Chat.Alert.Forward.ShowCaption': 'Show caption',
  'Chat.Alert.Forward.ShowSenderName': 'Show sender name',
  'Chat.CallMessage.TimeAndDuration': '%1$@, %2$@',
  'Chat.ChannelBadge': 'channel',
  'Chat.ClearHistory.Text': 'Are you sure you want to clear history?',
  'Chat.Close': 'Close Chat',
  'Chat.CommentsLabel': 'Comments',
  'Chat.Confirm.Unpin': 'Would you like to unpin this message?',
  'Chat.Context.LinkCopiedPrivate': 'Link copied. This link will only work for chat members.',
  'Chat.Context.ReactedFast': {
    other_value: '%d Reacted',
  },
  'Chat.Context.ReadLabel': 'Read',
  'Chat.Context.SearchSelected': 'Search Selected',
  'Chat.CopySelectedText': 'Copy Selected Text',
  'Chat.Date.ScheduledFor': 'Scheduled for %@',
  'Chat.Date.ScheduledForToday': 'Scheduled for today',
  'Chat.Delete.Channel.Text': 'The channel will be deleted for all subscribers.',
  'Chat.Delete.Group.Text': 'The group will be deleted for all members.',
  'Chat.Delete.Private.Text': 'This chat will be deleted from your chat list.',
  'Chat.DropAsFilesDesc': 'without compression',
  'Chat.DropQuickDesc': 'in a quick way',
  'Chat.DropTitle': 'Drop files here to send them',
  'Chat.Edit.Cancel.Text': 'Are you sure you want to discard all changes?',
  'Chat.ForwardedFrom': 'Forwarded from',
  'Chat.Frozen.LearnMore': 'Learn more...',
  'Chat.Input.Attach': 'Attach',
  'Chat.Input.Attach.Document': 'Document',
  'Chat.Input.Attach.PhotoOrVideo': 'Photo or Video',
  'Chat.Input.FrozenButton1': 'Your Account is Frozen',
  'Chat.Input.FrozenButton2': 'Click to view details',
  'Chat.Input.UnpinAll': 'Unpin All Messages',
  'Chat.Leave.Channel.Text': 'Are you sure you want to leave this channel?',
  'Chat.Leave.Group.Text': 'Are you sure you want to leave this group?',
  'Chat.LeaveChat': 'Leave chat',
  'Chat.Menu.ChangeTheme': 'Change Theme',
  'Chat.Menu.ClearSelection': 'Clear Selection',
  'Chat.Menu.Hint': 'To **edit** or **reply**, close this menu.\nThen tap next to a message.',
  'Chat.Menu.SelectMessages': 'Select Messages',
  'Chat.Menu.SendGift': 'Send a Gift',
  'Chat.MuteChat': 'Mute Chat',
  'Chat.OwnerBadge': 'owner',
  'Chat.Pinned.DontShow': 'Hide Pinned Messages',
  'Chat.Poll.MembersVoted': { one_value: '%d member voted', other_value: '%d members voted' },
  'Chat.Poll.SelectAnOption': 'Select an option',
  'Chat.Poll.Stop': 'Stop Poll',
  'Chat.Poll.SubmitVote': 'Vote',
  'Chat.Poll.TotalVotesEmpty': 'No votes yet',
  'Chat.Poll.TotalVotesResultEmpty': 'No votes',
  'Chat.Poll.Type.Anonymous': 'Anonymous Poll',
  'Chat.Poll.Type.AnonymousQuiz': 'Anonymous Quiz',
  'Chat.Poll.Type.Closed': 'Final Results',
  'Chat.Poll.Type.Public': 'Poll',
  'Chat.Poll.Type.Quiz': 'Quiz',
  'Chat.Poll.Unvote': 'Retract Vote',
  'Chat.Quiz.MembersAnswered': { one_value: '%d member answered', other_value: '%d members answered' },
  'Chat.Search.JoinedChannels': 'Channels you joined',
  'Chat.Search.NextResult': 'Next search result',
  'Chat.Search.NothingFound': 'Nothing interesting here yet...',
  'Chat.Search.PreviousResult': 'Previous search result',
  'Chat.Selection.Selected': 'Selected',
  'Chat.Send.ScheduledMessage': 'Schedule Message',
  'Chat.Send.SetReminder': 'Set a Reminder',
  'Chat.Send.WithoutSound': 'Send Without Sound',
  'Chat.SendAs.Anonymously': 'Anonymously',
  'Chat.SendAs.PersonalAccount': 'personal account',
  'Chat.SendAs.Title': 'Send As…',
  'Chat.SendAs.YourChannels': 'Your channels',
  'Chat.SendNow.Text': 'Send message now?',
  'Chat.SendNow.TextMultiple': {
    one_value: 'Send %d message now?',
    other_value: 'Send %d messages now?',
  },
  'Chat.SendNow.Title': 'Send Message Now',
  'Chat.SendNow.TitleMultiple': 'Send Messages Now',
  'Chat.Service.Call.Missed': 'Missed',
  'Chat.Title.Comments': {
    one_value: '%d Comment',
    other_value: '%d Comments',
  },
  'Chat.UnpinAll.Text': 'Are you sure you want to unpin all messages?',
  'Chat.UnpinAllMessagesConfirmation': {
    one_value: 'Do you want to unpin %d message in this chat?',
    other_value: 'Do you want to unpin all %d messages in this chat?',
  },
  'Chat.VoiceChat.JoinLink.Participants_ZeroValueHolder': 'no one joined yet',
  ChatAdmin: 'admin',
  'ChatAutomation.NewChats': 'New Chats',
  'ChatAutomation.Stop': 'Stop',
  ChatBackground: 'Chat Wallpaper',
  'ChatBackground.Blur': 'Blur Wallpaper Image',
  'ChatBackground.Title': 'Chat Background',
  'ChatBackground.UploadWallpaper': 'Upload Wallpaper',
  ChatHistory: 'Chat history for new members',
  ChatHistoryHint: 'New members will see earlier messages when this is on.',
  'ChatList.Context.DeleteChat': 'Delete Chat',
  'ChatList.Context.LeaveChannel': 'Leave Channel',
  'ChatList.Context.LeaveGroup': 'Leave Group',
  'ChatList.Context.Mute': 'Mute',
  'ChatList.Context.Pin': 'Pin',
  'ChatList.Context.Unmute': 'Unmute',
  'ChatList.Context.Unpin': 'Unpin',
  'ChatList.Filter.Bots': 'Bots',
  'ChatList.Filter.Channels': 'Channels',
  'ChatList.Filter.Confirm.Remove.Header': 'Remove Folder',
  'ChatList.Filter.Confirm.Remove.Text': 'Are you sure you want to remove this folder? Your chats will not be deleted.',
  'ChatList.Filter.Contacts': 'Contacts',
  'ChatList.Filter.Groups': 'Groups',
  'ChatList.Filter.Header': 'Create folders for different groups of chats and quickly switch between them.',
  'ChatList.Filter.Include.AddChat': 'Add Chats',
  'ChatList.Filter.List.Title': 'Chat Folders',
  'ChatList.Filter.MutedChats': 'Muted',
  'ChatList.Filter.NewTitle': 'Create Folder',
  'ChatList.Filter.NonContacts': 'Non-Contacts',
  'ChatList.Filter.ReadChats': 'Read',
  'ChatList.Main.EmptyPlaceholder.Subtitle': 'You have %s on Telegram',
  'ChatList.Main.EmptyPlaceholder.SubtitleNoContacts': 'Use Telegram app on your [Android](https://telegram.org/android) or [iOS](https://telegram.org/dl/ios) device to sync your contacts',
  'ChatList.Main.EmptyPlaceholder.Title': 'Your chats will appear here',
  'ChatList.Mute.1Day': 'For 1 Day',
  'ChatList.Mute.1Hour': 'For 1 Hour',
  'ChatList.Mute.3Days': 'For 3 Days',
  'ChatList.Mute.4Hours': 'For 4 Hours',
  'ChatList.Mute.8Hours': 'For 8 Hours',
  ChatLocation: 'Location',
  'ChatTheme.None': 'No Theme',
  'ChatTheme.Title': 'Chat Theme',
  ChatYourSelf: 'forward here to save',
  ChatYourSelfDescription1: 'Forward messages here to save them',
  ChatYourSelfDescription2: 'Send media and files to store them',
  ChatYourSelfDescription3: 'Access this chat from any device',
  ChatYourSelfDescription4: 'Use search to quickly find things',
  ChatYourSelfTitle: 'Your cloud storage',
  Chats: { one_value: '%1$d chat', other_value: '%1$d chats' },
  ChatsSelected: { one_value: '%d chat selected', other_value: '%d chats selected' },
  'Checkbox.Disabled': 'Disabled',
  'Checkbox.Enabled': 'Enabled',
  Checklist: 'Checklist',
  'Checklist.AddTask': 'Add a Task',
  'Checklist.NewTask': 'New task',
  'Checklist.Tasks': 'Tasks',
  'Checklist.Title.Label': 'Title',
  'Checklist.TitlePlaceholder': 'Checklist Title',
  ChecklistAllowOthersAdd: 'Allow Others to Add Tasks',
  ChecklistAllowOthersDone: 'Allow Others to Mark as Done',
  'Checkout.PasswordEntry.Pay': 'Pay',
  Clear: 'Clear',
  ClearButton: 'Clear',
  ClearHistory: 'Clear history',
  ClearOtherSessionsHelp: 'Logs out all devices except for this one.',
  ClearRecentSearch: 'clear',
  ClearRecentStickersAlertTitle: 'Clear recent stickers',
  'ClientPip.Exit': 'Exit Picture-in-Picture',
  Close: 'Close',
  'CloseFriends.Title': 'Close Friends',
  'CloseFriends.Updated': 'Close friends list updated',
  CloseTopic: 'Close topic',
  ColorTheme: 'Color theme',
  Comment: 'Comment',
  'Comments': {
    one_value: '%1$d Comment',
    other_value: '%1$d Comments',
  },
  'Common.Back': 'Back',
  'Common.Creating': 'Creating…',
  'Common.Menu': 'Menu',
  'Common.More': 'More',
  'Common.Of': 'of',
  'Common.Tag': 'Tag',
  'Composer.CancelRecording': 'Cancel Recording',
  'Composer.DiscardVoice.Text': 'Are you sure you want to discard this voice message?',
  'Composer.Formatting': 'Formatting',
  'Composer.MediaRestricted': 'Media is not allowed in this group',
  'Composer.MessageEffect': 'Message effect',
  'Composer.RecordRound': 'Record video message',
  'Composer.RecordVoice': 'Record voice message',
  'ConferenceCall.Media.CameraError': 'Could not change the camera state. Check camera access and try again.',
  'ConferenceCall.Media.MicrophoneError':
    'Could not change the microphone state. Check microphone access and try again.',
  'ConnectionStatus.ReconnectInPlain': 'Reconnect in %ds',
  'ConnectionStatus.Reconnecting': 'Reconnecting...',
  'ConnectionStatus.Waiting': 'Waiting for network...',
  ContactNoteRow: 'Notes',
  Contacts: 'Contacts',
  'Contacts.Count': { one_value: '%d contact', other_value: '%d contacts' },
  'Contacts.Empty': 'No contacts',
  Continue: 'Continue',
  Copy: 'Copy',
  CopyLink: 'Copy Link',
  Country: 'Country',
  Create: 'Create',
  CreateANew: 'Create a New',
  'CreateBot.Username.Taken': 'This username is already taken.',
  'CreateGroup.NameHolder': 'Group Name',
  CreateNewLink: 'Create a New Link',
  CurrentSession: 'This device',
  DataSettings: 'Data and Storage',
  'Date.Today': 'Today',
  Days: {
    one_value: '%1$d day',
    other_value: '%1$d days',
  },
  Delete: 'Delete',
  DeleteAllRevokedLinks: 'Delete All Revoked Links',
  DeleteAndExitButton: 'Delete and Leave Group',
  DeleteChannelForAll: 'Delete for all subscribers',
  'DeleteChat.DeleteGroupForAll': 'Delete for all members',
  DeleteChatUser: 'Delete chat',
  DeleteContact: 'Delete contact',
  DeleteContactsSubtitle: 'Are you sure you want to delete these contacts?',
  DeleteContactsTitle: { one_value: 'Delete %d contact', other_value: 'Delete %d contacts' },
  DeleteForEveryone: 'Delete for everyone',
  DeleteForMe: 'Delete for me',
  DeleteLink: 'Delete Link',
  DeleteMega: 'Delete Group',
  DeleteMegaMenu: 'Delete group',
  DeleteMessagesCount: {
    one_value: 'Delete %d message',
    other_value: 'Delete %d messages',
  },
  DeleteMessagesOptionAlso: 'Also delete for %1$s',
  DeleteMessagesTitle: 'Delete %1$s',
  DeleteSingleMessagesTitle: 'Delete message',
  DeleteStorySubtitle: 'Are you sure you want to delete this story?',
  DeleteStoryTitle: 'Delete Story',
  DeletedMessage: 'Deleted message',
  DescriptionOptionalPlaceholder: 'Description (optional)',
  DescriptionPlaceholder: 'Description',
  Devices: 'Devices',
  Disable: 'Disable',
  DisableAnimations: 'Disable Animations',
  DisableDarkMode: 'Disable Dark Mode',
  DisablePhotoSpoiler: 'Remove spoiler',
  DisableSharing: 'Disable Sharing',
  Discard: 'Discard',
  DiscardVoiceMessageTitle: 'Discard Voice Message',
  // Ключ СВОЙ, хотя у оригинала есть `Discussion.Set.Modal.Text.PublicChannelPublicGroup`:
  // там ДВА аргумента в формате `%@` (имя группы и имя канала), которого не заполняет ни
  // наш `tArgs`, ни `superFormatter` самого tweb, а у нашего экрана аргумент один.
  'Discussion.Link.Question': 'Do you want to set «%1$s» as the discussion board for this channel?',
  'Discussion.Linked': 'Users can now discuss your posts in the linked group.',
  'Discussion.Unlink.Text': 'Are you sure you want to unlink this group from the channel?',
  DiscussionChannelHelp3: 'Select a group chat that will host comments from your channel.',
  DiscussionCreateGroup: 'Create a New Group',
  DiscussionInfo: 'Add a group chat for comments',
  DiscussionLinkGroup: 'Link Group',
  DiscussionStarted: 'Discussion started',
  DiscussionUnlink: 'Unlink',
  DiscussionUnlinkGroup: 'Unlink Group',
  DoNotForward: 'Do Not Forward',
  DoNotTranslate: 'Do Not Translate',
  Done: 'Done',
  DoubleTapSetting: 'Quick Reaction',
  Draft: 'Draft',
  Edit: 'Edit',
  'EditAccount.Logout': 'Log Out',
  'EditAccount.Title': 'Edit Profile',
  'EditAccount.Username': 'Username',
  EditAdmin: 'Admin Rights',
  EditAdminAddAdmins: 'Add New Admins',
  EditAdminAddUsersViaLink: 'Invite Users via Link',
  EditAdminBanUsers: 'Ban Users',
  EditAdminCantEdit: 'You can\'t edit the rights of this admin.',
  EditAdminChangeChannelInfo: 'Change Channel Info',
  EditAdminChangeGroupInfo: 'Change Group Info',
  EditAdminDeleteMessages: 'Delete Messages of Others',
  EditAdminEditMessages: 'Edit Messages of Others',
  EditAdminGroupDeleteMessages: 'Delete Messages',
  EditAdminPinMessages: 'Pin Messages',
  EditAdminPostMessages: 'Post Messages',
  EditAdminRights: 'Edit admin rights',
  EditAdminWhatCanDo: 'What can this admin do?',
  EditCantEditPermissions: 'You cannot change this permission.',
  EditCantEditPermissionsPublic: 'This permission is not available in public groups.',
  'EditContact.OriginalName': 'original name',
  EditFactCheck: 'Edit Fact Check',
  'EditFolder.EmojiAsIconTip': 'If you put only one emoji at the beginning (or at the end), it will be displayed as the icon in the folders sidebar',
  'EditFolder.Toast.ChooseChat': 'Please choose at least one chat for this folder.',
  'EditInvitation.ExpiryDate': 'Expiry Date',
  'EditInvitation.Never': 'Never',
  'EditInvitation.NumberOfUsers': 'Number of Users',
  'EditInvitation.Unlimited': 'Unlimited',
  'EditProfile.AddBirthdayRow': 'Add Birthday',
  'EditProfile.BioLabel': 'Bio (optional)',
  'EditProfile.FirstNameLabel': 'Name',
  'EditProfile.Username.Available': 'Username is available',
  'EditProfile.Username.Invalid': 'Username is invalid',
  'EditProfile.Username.Label': 'Username (optional)',
  'EditProfile.Username.Taken': 'Username is already taken',
  EditedMessage: 'edited',
  'Effect.Remove': 'Remove Effect',
  Emoji: 'Emoji',
  'Emoji.Activity': 'Activity',
  'Emoji.AnimalsAndNature': 'Animals & Nature',
  'Emoji.Flags': 'Flags',
  'Emoji.FoodAndDrink': 'Food & Drink',
  'Emoji.Objects': 'Objects',
  'Emoji.Recent': 'Frequently Used',
  'Emoji.SmilesAndPeople': 'Smileys & People',
  'Emoji.Symbols': 'Symbols',
  'Emoji.TravelAndPlaces': 'Travel & Places',
  'EmojiStatus.Set': 'Set Emoji Status',
  EnableAnimations: 'Enable Animations',
  EnableDarkMode: 'Enable Dark Mode',
  EnablePhotoSpoiler: 'Hide with spoiler',
  EnterChannelName: 'Channel name',
  'Error.AnError': 'An error occurred. Please try again later.',
  'Error.SomethingWentWrong': 'Something went wrong',
  'ExportedInvitation.Status.Expired': 'expired',
  'ExportedInvitation.Status.Revoked': 'revoked',
  FactCheck: 'Fact Check',
  'FactCheck.AdminNote': 'This fact check was added by an admin.',
  'FactCheck.CountryPlaceholder': 'Country code (optional)',
  'FactCheck.Delete': 'Delete Fact Check',
  FactCheckDeleted: 'Fact check removed.',
  FactCheckDialog: 'Fact Check',
  FactCheckEdited: 'Fact check updated.',
  FactCheckPlaceholder: 'Add Fact or Context',
  FavoriteStickers: 'Favorites',
  FilterAllBots: 'All Bots',
  FilterAllChannels: 'All Channels',
  FilterAllChats: 'All Chats',
  FilterAllChatsShort: 'All',
  FilterAllContacts: 'All Contacts',
  FilterAllGroups: 'All Groups',
  FilterAllNonContacts: 'All Non-Contacts',
  FilterAlwaysShow: 'Include Chats',
  FilterChatTypes: 'Chat types',
  FilterChats: 'Chats',
  FilterEdit: 'Edit folder',
  FilterEditAll: 'Edit folders',
  FilterExclude: 'Excluded Chats',
  FilterExcludeInfo: 'Choose chats or types of chats that will not appear in this folder.',
  FilterHeaderEdit: 'Edit Folder',
  FilterInclude: 'Included Chats',
  FilterIncludeExcludeInfo: 'Choose chats and types of chats that will\nappear and never appear in this folder.',
  FilterIncludeInfo: 'Choose chats or types of chats that will appear in this folder.',
  FilterMenuDelete: 'Delete Folder',
  FilterNameHint: 'Folder name',
  FilterNeverShow: 'Exclude Chats',
  FilterNew: 'New Folder',
  FilterNoChatsToDisplay: 'Folder is empty',
  FilterNoChatsToDisplayInfo: 'No chats currently belong to this folder.',
  FilterRemoveChats: 'Remove Chats',
  FilterShowMoreChats: { one_value: 'Show %1$d More Chat', other_value: 'Show %1$d More Chats' },
  Filters: 'Folders',
  FiltersOnLeft: 'Folders on the Left',
  FiltersOnTop: 'Folders above chats',
  FiltersView: 'Folders view',
  FirstName: 'First name (required)',
  'Folder.Added': 'Folder added',
  'Folder.Invite.Adding': 'Adding…',
  'Folder.Invite.Invalid': 'This link is invalid or has expired.',
  // Ключ СВОЙ, хотя у оригинала есть `SharedFolder.Link.Description`: у него нет
  // аргумента вовсе («…a new chat folder…»), а наш экран называет папку по имени.
  'Folder.Invite.Question': 'Do you want to add «%1$s» and join its chats?',
  'Folder.Invite.Question.Folder': 'Do you want to add the folder «%1$s»?',
  'ForumTopic.Closed': 'Topic is closed',
  'ForumTopic.Context.New': 'Create Topic',
  'ForumTopic.Context.ShowAsMessages': 'View as Messages',
  'ForumTopic.Created': 'Topic created',
  'ForumTopic.EnableHint': 'Group members can discuss different topics in separate threads.',
  'ForumTopic.Hidden': 'Hidden Topics',
  'ForumTopic.Name.Placeholder': 'Topic Name',
  'ForumTopic.NoIcon': 'No icon',
  'ForumTopic.Title.Edit': 'Edit Topic',
  'ForumTopic.Unhide': 'Unhide',
  Forward: 'Forward',
  FromYou: 'You',
  FwdMessageTo: 'Message forwarded to %s.',
  FwdMessageToSavedMessages: 'Message forwarded to **Saved Messages**.',
  FwdMessagesTo: 'Messages forwarded to %s.',
  FwdMessagesToChats: {
    other_value: '%d chats',
  },
  FwdMessagesToSavedMessages: 'Messages forwarded to **Saved Messages**.',
  General: 'General',
  'General.TextSize': 'Text Size',
  'General.TimeFormat': 'Time Format',
  'General.TimeFormat.h12': '12-hour',
  'General.TimeFormat.h23': '24-hour',
  'GeneralSettings.EmojiPrediction': 'Suggest Emoji',
  'Gif.Delete': 'Delete GIF',
  'Gif.Save': 'Save GIF',
  'Gif.Saved': 'GIF saved to your GIFs.',
  'Gif.Trending': 'Trending',
  'Giveaway.Create': 'Create Giveaway',
  'Giveaway.DurationHint': 'Giveaway can last up to 7 days.',
  'Giveaway.New': 'New Giveaway',
  'Giveaway.Participate': 'Participate',
  'Giveaway.Participating': 'You are participating',
  'Giveaway.Prize': 'Prize',
  'Giveaway.StarsPerWinner': 'Stars per winner',
  'Giveaway.WinnersSelected': 'Winners selected',
  'Giveaway.YouWon': 'You won the giveaway!',
  GlobalAttachMediaRestricted: 'Sending media isn\'t allowed in this group.',
  GlobalSearch: 'Global search',
  GlobalSendMessageRestricted: 'Sending messages is not allowed in this group.',
  Group: 'Group',
  'Group.MemberBadge': 'Member',
  'Group.RestrictedBadge': 'Restricted',
  GroupAddMembers: 'Add Members',
  'GroupCall.Participants': 'Participants',
  GroupChecklist: 'Group Checklist',
  GroupType: 'Group Type',
  Groups: { one_value: '%1$d group', other_value: '%1$d groups' },
  GroupsOnly: 'Group Chats',
  Hide: 'Hide',
  HideReadTime: 'Hide Read Time',
  HideReadTimeInfo: 'Hide the time when you read messages from people who can’t see your last seen. If you turn this on, their read time will also be hidden from you (unless you are a Premium user).\n\nThis setting does not affect group chats.',
  // Пара к `Days`/`Weeks`/`Months`/`Years`: срок ограничения участника считает часы
  // (tweb lang.ts:1675 — текст и формы взяты у оригинала дословно).
  Hours: {
    one_value: '%1$d hour',
    other_value: '%1$d hours',
  },
  'InactiveChannel.Broadcast': 'channel',
  'InactiveChannel.Group': 'group',
  Info: 'Info',
  'InstalledStickers.LoopAnimated': 'Loop Animated Stickers',
  'InstantView.OpenInBrowser': 'Open in browser',
  InviteLink: 'Invite Link',
  'InviteLink.AdminApproval.Disabled': 'You can\'t enable admin approval for links that require a monthly fee.',
  'InviteLink.JoinedNew': {
    other_value: '%d joined',
  },
  'InviteLink.JoinedRevoked': 'no one joined',
  'InviteLink.Sticker.TimeLeft': 'expires in %@',
  InviteLinks: 'Invite Links',
  'InviteLinks.Additional': 'Additional Links',
  'InviteLinks.Description': 'You can create additional invite links that are limited by time, number of users, or require a paid subscription.',
  'InviteLinks.Edit': 'Edit Link',
  'InviteLinks.ExpiresCaption': 'This link expires %s.',
  'InviteLinks.LimitReached': 'limit reached',
  'InviteLinks.Reactivate': 'Reactivate Link',
  InviteToGroupError: 'Sorry, you can\'t add this user to groups because of user\'s privacy settings.',
  JumpToDate: 'Jump to Date',
  'KeyboardShortcuts.Action.Bold': 'Bold',
  'KeyboardShortcuts.Action.ClosePopup': 'Close popup or menu',
  'KeyboardShortcuts.Action.CloseStories': 'Close stories',
  'KeyboardShortcuts.Action.EditLast': 'Edit last message',
  'KeyboardShortcuts.Action.Italic': 'Italic',
  'KeyboardShortcuts.Action.Link': 'Add Link',
  'KeyboardShortcuts.Action.Monospace': 'Monospace',
  'KeyboardShortcuts.Action.NewLine': 'New line',
  'KeyboardShortcuts.Action.NextChat': 'Next chat',
  'KeyboardShortcuts.Action.NextMedia': 'Next media',
  'KeyboardShortcuts.Action.NextStory': 'Next story',
  'KeyboardShortcuts.Action.OpenSearch': 'Open search',
  'KeyboardShortcuts.Action.PlayPauseStory': 'Play / pause story',
  'KeyboardShortcuts.Action.PreviousChat': 'Previous chat',
  'KeyboardShortcuts.Action.PreviousMedia': 'Previous media',
  'KeyboardShortcuts.Action.PreviousStory': 'Previous story',
  'KeyboardShortcuts.Action.Redo': 'Redo',
  'KeyboardShortcuts.Action.ReplyToPrevious': 'Reply to previous message',
  'KeyboardShortcuts.Action.SavedMessages': 'Open Saved Messages',
  'KeyboardShortcuts.Action.Send': 'Send message',
  'KeyboardShortcuts.Action.Spoiler': 'Spoiler',
  'KeyboardShortcuts.Action.Strikethrough': 'Strikethrough',
  'KeyboardShortcuts.Action.Underline': 'Underline',
  'KeyboardShortcuts.Action.Undo': 'Undo',
  'KeyboardShortcuts.Action.ZoomIn': 'Zoom in',
  'KeyboardShortcuts.Action.ZoomOut': 'Zoom out',
  'KeyboardShortcuts.Hint.WhenInputEmpty': 'when input is empty',
  'KeyboardShortcuts.Section.Chat': 'Chat',
  'KeyboardShortcuts.Section.Formatting': 'Text Formatting',
  'KeyboardShortcuts.Section.Formatting.Caption': 'Select text in the chat input to apply formatting.',
  'KeyboardShortcuts.Section.MediaEditor': 'Media Editor',
  'KeyboardShortcuts.Section.MediaViewer': 'Media Viewer',
  'KeyboardShortcuts.Section.Messages': 'Messages',
  'KeyboardShortcuts.Section.Navigation': 'Navigation',
  'KeyboardShortcuts.Section.Stories': 'Stories',
  'KeyboardShortcuts.Title': 'Keyboard Shortcuts',
  KickFromGroup: 'Remove from group',
  // Имя ЭТОГО языка на нём самом: единственный ключ, чей перевод — не перевод
  // текста, а самоназвание. Им подписана строка «Язык» в настройках, как у tweb
  // (`sidebarLeft/tabs/settings.tsx:254` — `i18n('LanguageName')`); списка
  // языков для этого не нужно.
  KickFromSupergroup: 'Restrict user',
  LanguageName: 'English',
  LastName: 'Last name (optional)',
  'LastSeen.HoursAgo': {
    one_value: 'last seen %d hour ago',
    other_value: 'last seen %d hours ago',
  },
  LastSeenTitle: 'Who can see my Last Seen time?',
  Lately: 'last seen recently',
  'LeaveAComment': 'Leave a comment',
  LeaveChannel: 'Leave Channel',
  LeaveChannelMenu: 'Leave channel',
  LeaveMegaMenu: 'Leave group',
  LimitByPeriod: 'Limit by time period',
  LimitNumberOfUses: 'Limit by number of users',
  LimitReached: 'Limit Reached',
  'Link.Available': 'Link is available',
  'Link.Invalid': 'Link is invalid',
  'Link.Taken': 'Link is already taken',
  LinkCopied: 'Link copied to clipboard',
  LinkCreatedeBy: 'Link created by',
  LinkIsExpired: 'The time limit for this link has expired.',
  LinkIsExpiredLimitReached: 'This link reached its usage limit.',
  LinkNameHelp: 'Only admins will see this name.',
  LinkNameHint: 'Link Name (Optional)',
  'LiteMode.DisableAlert': 'Disable Power Saving Mode',
  'LiteMode.EnableText': 'Power Saving Mode',
  'LiteMode.Info': 'Reduce all power-intensive animations and improve performance.',
  'LiteMode.Key.animations.Title': 'Interface Animations',
  'LiteMode.Key.blur.Title': 'Blur Effects',
  'LiteMode.Key.chat.Title': 'Chat Animations',
  'LiteMode.Key.chat_background.Title': 'Wallpaper rotation',
  'LiteMode.Key.chat_spoilers.Title': 'Animated spoiler effect',
  'LiteMode.Key.effects.Title': 'Interactive Effects',
  'LiteMode.Key.effects_emoji.Title': 'Emoji effect',
  'LiteMode.Key.effects_premiumstickers.Title': 'Premium stickers effect',
  'LiteMode.Key.effects_reactions.Title': 'Reaction effect',
  'LiteMode.Key.emoji_appear.Title': 'Emoji appear effect',
  'LiteMode.Key.gif.Title': 'Autoplay GIFs',
  'LiteMode.Key.stickers.Title': 'Sticker Animations',
  'LiteMode.Key.stickers_chat.Title': 'Autoplay in chat',
  'LiteMode.Key.stickers_panel.Title': 'Autoplay in panel',
  'LiteMode.Key.video.Title': 'Autoplay Videos',
  'LiteMode.Title': 'Power Saving',
  'Livestream.Ended': 'Ended',
  'Livestream.IsLive': 'The stream is live',
  'Livestream.Recording': 'Recording',
  'Livestream.Start': 'Start Live Stream',
  Loading: 'Loading...',
  LogOut: 'Log out',
  'Login.Code.Expired': 'Code expired. Please request a new one.',
  'Login.Code.SentSms': 'We have sent you an SMS\nwith the code.',
  'Login.Error.FloodWait': 'Too many attempts. Please try again later.',
  'Login.Error.Generic': 'Something went wrong. Try again.',
  'Login.ForgotPassword': 'Forgot Password?',
  'Login.Next': 'Next',
  'Login.Passkey': 'Log in by passkey >',
  'Login.Passkey.Action': 'Log in with a Passkey',
  'Login.Passkey.Error': 'Something went wrong',
  'Login.Password.Subtitle': 'Your account is protected with\nan additional password',
  'Login.Password.Title': 'Enter Your Password',
  'Login.PhoneLabel': 'Phone Number',
  'Login.PhoneLabelInvalid': 'Phone Number Invalid',
  'Login.QR.Cancel': 'Log in by phone number >',
  'Login.QR.Help1': 'Open Telegram on your phone',
  'Login.QR.Help2': 'Go to **Settings** > **Devices** > **Add Device**',
  'Login.QR.Help3': 'Point your phone at this screen to confirm login',
  'Login.QR.Subtitle': 'Scan with Telegram app on your phone',
  'Login.QR.Title': 'Log in by QR Code',
  'Login.Register.LastName.Placeholder': 'Last Name',
  'Login.Register.NameRequired': 'Please enter your name',
  'Login.Register.NameTooLong': 'Name is too long',
  'Login.Register.Subtitle': 'Enter your name and add\na profile photo',
  'Login.ResetAccount.Text': 'This action can\'t be undone.\n\nIf you reset your account, all your messages and chats will be deleted.',
  'Login.ResetAccount.Title': 'Warning',
  'Login.ResetAccountFail.Title': 'Sorry',
  'Login.ResetPassword.HasEmail': 'A recovery email is linked to this account — reset it by email instead.',
  'Login.ResetPassword.NoEmailText': 'Since you didn\'t provide a recovery email when setting up your password, your remaining options are either to remember your password or to reset your account.',
  'Login.ResetPassword.ResetAccount': 'Reset Account',
  'Login.ResetPassword.Subtitle': 'Enter the code we just sent\nto your email **%s**.',
  'Login.ResetPassword.Title': 'Reset Password',
  'Login.SessionExpired': 'Session expired. Please sign in again.',
  'Login.StartText': 'Please confirm your country code\nand enter your phone number.',
  'Login.Title': 'Sign in to Telegram',
  LoginEmail: 'Login Email',
  'LoginEmail.Caption': 'This email is used to log in if you lose access to your number.',
  'LoginEmail.Change': 'Change Login Email',
  LoginPassword: 'Password',
  LoopAnimatedStickersInfo: 'Animated stickers will play continuously in chats.',
  'ManageLinks.DeleteAll.Confirm': 'Are you sure you want to delete all revoked links?',
  MarkAsRead: 'Mark as read',
  'MarkupTooltip.LinkPlaceholder': 'Enter URL...',
  'Media.Pause': 'Pause',
  'Media.Play': 'Play',
  MediaCopied: 'Media copied to clipboard',
  MediaCopyFailed: 'Failed to copy media to clipboard',
  'MediaEditor.Adjustments.Brightness': 'Brightness',
  'MediaEditor.Adjustments.Contrast': 'Contrast',
  'MediaEditor.Adjustments.Enhance': 'Enhance',
  'MediaEditor.Adjustments.Fade': 'Fade',
  'MediaEditor.Adjustments.Grain': 'Grain',
  'MediaEditor.Adjustments.Highlights': 'Highlights',
  'MediaEditor.Adjustments.Saturation': 'Saturation',
  'MediaEditor.Adjustments.Shadows': 'Shadows',
  'MediaEditor.Adjustments.Sharpen': 'Sharpen',
  'MediaEditor.Adjustments.Vignette': 'Vignette',
  'MediaEditor.Adjustments.Warmth': 'Warmth',
  'MediaEditor.AspectRatio': 'Aspect ratio',
  'MediaEditor.BrushSize': 'Brush size',
  'MediaEditor.Brushes.Arrow': 'Arrow',
  'MediaEditor.Brushes.Blur': 'Blur',
  'MediaEditor.Brushes.Brush': 'Marker',
  'MediaEditor.Brushes.Eraser': 'Eraser',
  'MediaEditor.Brushes.Neon': 'Neon',
  'MediaEditor.Brushes.Pen': 'Pen',
  'MediaEditor.Cover': 'Cover',
  'MediaEditor.Crop': 'Crop',
  'MediaEditor.Discard.Text': 'Are you sure you want to discard the changes?',
  'MediaEditor.DiscardChanges': 'Discard Changes',
  'MediaEditor.Draw': 'Draw',
  'MediaEditor.Flip': 'Flip',
  'MediaEditor.Font': 'Font',
  'MediaEditor.Free': 'Free',
  'MediaEditor.Mute': 'Mute video',
  'MediaEditor.Original': 'Original',
  'MediaEditor.RecentlyUsed': 'Recently Used',
  'MediaEditor.Rotate': 'Rotate',
  'MediaEditor.Square': 'Square',
  'MediaEditor.StickerAnimatedUnsupported': 'Animated stickers are not supported in this browser',
  'MediaEditor.StickerNotRendered': 'This sticker cannot be rendered in this browser and will not be saved. Remove it to continue.',
  'MediaEditor.TextSize': 'Text size',
  'MediaEditor.Tool': 'Tool',
  'MediaEditor.Unmute': 'Unmute video',
  'MediaViewer.Context.Copy': 'Copy Media',
  'MediaViewer.Context.Download': 'Download',
  MegaPrivate: 'Private Group',
  MegaPrivateInfo: 'Private groups can only be joined if you were invited or have an invite link.',
  MegaPrivateLinkHelp: 'People can join your group by following this link. You can revoke the link any time.',
  MegaPublic: 'Public Group',
  MegaPublicInfo: 'Public groups can be found in search, chat history is available to everyone and anyone can join.',
  Members: {
    one_value: '%1$d member',
    other_value: '%1$d members',
  },
  MenuTelegramStars: 'My Stars',
  Message: 'Message',
  'Message.Context.Goto': 'Show in chat',
  'Message.Context.Pin': 'Pin',
  'Message.Context.Select': 'Select',
  'Message.Context.Selection.Clear': 'Clear selection',
  'Message.Context.Selection.Copy': 'Copy selected',
  'Message.Context.Selection.Delete': 'Delete selected',
  'Message.Context.Selection.Download': 'Download selected',
  'Message.Context.Selection.Forward': 'Forward selected',
  'Message.Context.Unpin': 'Unpin',
  'Message.Preview.Call': 'Call',
  'Message.Unsupported': 'Unsupported message',
  'MessageContext.CopyMessageLink1': 'Copy Message Link',
  MessagePreview: 'Message Preview',
  MessageScheduleEditTime: 'Reschedule',
  MessageScheduleSend: 'Send Now',
  MessageScheduledUntilOnline: 'Scheduled until online',
  MessageSeen: {
    one_value: 'Seen',
    other_value: '%1$d Seen',
  },
  Minutes: {
    one_value: '%1$d minute',
    other_value: '%1$d minutes',
  },
  MinutesShort: { one_value: '%1$d min', other_value: '%1$d min' },
  MobileHidden: 'Mobile hidden',
  MobileHiddenExceptionInfo: 'Phone number will be visible once %1$s adds you as a contact.',
  Months: {
    one_value: '%1$d month',
    other_value: '%1$d months',
  },
  MoreBoosts: {
    one_value: '**%d** more boost',
    other_value: '**%d** more boosts',
  },
  MoreSimilar: 'More Channels',
  'MultiAccount.AddAccount': 'Add Account',
  'MultiAccount.More': 'More',
  MyNotes: 'My Notes',
  'MyStories.Archive.Empty': 'No archived stories',
  'MyStories.Archive.Title': 'Stories Archive',
  'MyStories.Title': 'My Stories',
  MyStory: 'My Story',
  Never: 'Never',
  New: 'New',
  NewChannel: 'New Channel',
  NewChecklist: 'New Checklist',
  'NewChecklist.TaskPlaceholder': 'Task',
  'NewContact.Exception.ShareMyPhoneNumber': 'Share My Phone Number',
  'NewContact.Exception.ShareMyPhoneNumber.Desc': 'You can make your phone visible to %@.',
  NewGroup: 'New Group',
  NewLink: 'New Link',
  NewPoll: 'New Poll',
  'NewPoll.Anonymous': 'Anonymous Voting',
  'NewPoll.MultipleChoice': 'Multiple Answers',
  'NewPoll.Option': 'Option',
  'NewPoll.OptionsAddOption': 'Add an Option',
  'NewPoll.Quiz': 'Quiz Mode',
  'NewPoll.QuizHint': 'Select the correct answer in the list of options.',
  NewPrivateChat: 'New Private Chat',
  NewTopic: 'New Topic',
  NoEmojiFound: 'No emoji found',
  NoGIFsFound: 'No GIFs found',
  NoMessages: 'No messages here yet...',
  NoMessagesGreetingsDescription: 'Send a message or tap the greeting below.',
  NoReactions: 'No reactions',
  NoRecentCalls: 'No recent calls',
  NoRecentCallsInfo: 'Your recent voice and video calls will appear here.',
  NoResult: 'No results',
  NoResultsSubtitle: 'Try a different search term',
  NoResultsTitle: 'No results',
  NoScheduledMessages: 'No scheduled messages here yet...',
  NoStickersFound: 'No stickers found',
  NoTopics: 'No topics',
  NoUsernameFound: 'There is no Telegram account with this username.',
  NobodyViewed: 'Nobody viewed',
  Notifications: 'Notifications',
  'Notifications.Count': { one_value: '%d notification', other_value: '%d notifications' },
  'Notifications.Default': 'Give Telegram permission to send notifications. You may need to refresh the page to see the changes.',
  'Notifications.Enable': 'Enable Notifications',
  'Notifications.New': 'New notification',
  'Notifications.Offline': 'Show offline notifications',
  'Notifications.Restricted': 'You have restricted notifications. Reset permission in your browser and try again.',
  'Notifications.Show': 'Show notifications',
  'Notifications.Sound': 'Notification Sound',
  'Notifications.Sound.Caption': 'Drag and release or click to test the volume.',
  'Notifications.Sound.Effects': 'Sound Effects',
  'Notifications.Sound.Section': 'Sound',
  'Notifications.Sound.Sent': 'Message Sent',
  'Notifications.Sound.Volume': 'Sound Volume',
  'Notifications.Web': 'Web Notifications',
  NotificationsChannels: 'Channels',
  NotificationsForChannels: 'Notifications for channels',
  NotificationsForGroups: 'Notifications for groups',
  NotificationsForPrivateChats: 'Notifications for private chats',
  NotificationsGroups: 'Groups',
  NotificationsPrivateChats: 'Private Chats',
  OK: 'OK',
  Of: '%1$d of %2$d',
  Off: 'Off',
  Online: 'online',
  OnlineCount: {
    one_value: '%1$d online',
    other_value: '%1$d online',
  },
  OnlyAllowThisReactions: 'Only allow these reactions',
  Open: 'Open',
  OpenChat: 'Open Chat',
  OpenInNewTab: 'Open in new tab',
  OpenStory: 'OPEN STORY',
  OpenUrlAlert2: 'Do you want to open %1$s?',
  OpenUrlTitle: 'Open Link',
  Other: 'Other',
  OtherSessions: 'Active sessions',
  PASSWORD_HASH_INVALID: 'Incorrect password',
  PHONE_CODE_INVALID: 'Invalid code',
  'PWA.Install': 'Install App',
  'PaidMedia.MakePaid': 'Make paid',
  'PaidMedia.NotEnoughStars': 'Not enough Stars to unlock',
  'PaidMedia.PriceHint': 'Set a price in Stars — recipients unlock the media by paying you.',
  'PaidMedia.Title': 'Paid Content',
  'PaidMedia.UnlockFor': 'Unlock for',
  'PaidMedia.Unlocking': 'Unlocking…',
  'PaidMessages.ChargeForGroupMessagesDescription': 'If you turn this on, regular members of the group will have to pay Stars to send messages.',
  'PaidMessages.ChargeForMessages': 'Charge for Messages',
  'PaidMessages.SetPrice': 'Set your price per message',
  'PasscodeLock.AutoLock': 'Auto-lock after',
  'PasscodeLock.ChangePasscode': 'Change passcode',
  'PasscodeLock.Description': 'When a passcode is set, a lock icon appears above your chat list. Tap it to lock your Telegram.',
  'PasscodeLock.Disabled': 'Disabled',
  'PasscodeLock.EnableLockShortcut': 'Enable lock shortcut',
  'PasscodeLock.EnterANewPasscode': 'Enter a new passcode',
  'PasscodeLock.EnterAPasscode': 'Enter a passcode',
  'PasscodeLock.EnterYourPasscode': 'Enter your passcode',
  'PasscodeLock.ForgotPasscode.MultipleAccounts': 'Note: if you forget your passcode, you\'ll need to [log out]() from all your current accounts.',
  'PasscodeLock.ForgotPasscode.OneAccount': 'Note: if you forget your passcode, you\'ll need to [log out]().',
  'PasscodeLock.Item.Title': 'Passcode Lock',
  'PasscodeLock.LockShortcutDescription': 'Play around to find the perfect shortcut to work for your browser.',
  'PasscodeLock.LogoutPopup.Description': 'Are you sure you want to log out?',
  'PasscodeLock.Next': 'Next',
  'PasscodeLock.Notice': 'Note: If you forget your passcode, you\'ll need to log out.',
  'PasscodeLock.PasscodeHasBeenChanged': 'Passcode has been changed.',
  'PasscodeLock.PasscodeHasBeenDisabled': 'Passcode has been disabled.',
  'PasscodeLock.PasscodeHasBeenSet': 'Passcode has been set.',
  'PasscodeLock.PasscodesDontMatch': 'Passcodes don’t match, try again',
  'PasscodeLock.Proceed': 'Proceed',
  'PasscodeLock.ReEnterPasscode': 'Re-enter the passcode',
  'PasscodeLock.SetPasscode': 'Set passcode',
  'PasscodeLock.TapToLock': 'Tap to lock Telegram.',
  'PasscodeLock.Title': 'Passcode',
  'PasscodeLock.TooManyAttempts': 'Too many attempts, try again later',
  'PasscodeLock.TurnOff': 'Turn Off',
  'PasscodeLock.TurnOff.Description': 'Are you sure you want to turn passcode off?',
  'PasscodeLock.TurnOff.Title': 'Turn Passcode Off',
  'PasscodeLock.TurnOn': 'Turn Passcode On',
  'PasscodeLock.WrongPasscode': 'Wrong passcode. Please try again.',
  'Passkey.Created': 'Passkey created successfully',
  'Passkey.CreationError': 'Failed to create passkey. Please try again.',
  'Passkey.Deletion.Text': 'Once deleted, this passkey can\'t be used to log in.\n\nDon\'t forget to remove it from your password manager too.',
  'Passkey.Deletion.Title': 'Delete Passkey?',
  'Passkey.Row1.Subtitle': 'Make a passkey to log in easily and safely.',
  'Passkey.Row1.Title': 'Create a Passkey',
  'Passkey.Row2.Subtitle': 'Use Face ID, Touch ID, or your passcode to log in.',
  'Passkey.Row2.Title': 'Log in with Face ID',
  'Passkey.Row3.Subtitle': 'Your passkey is safely kept in your iCloud Keychain.',
  'Passkey.Row3.Title': 'Store Passkey Securely',
  'Passkey.Subtitle': 'Log in safely and keep your account secure.',
  'Passkey.Title': 'Protect your account',
  'Passkey.Unsupported': 'UNSUPPORTED',
  Passkeys: {
    one_value: '%d passkey',
    other_value: '%d passkeys',
  },
  PasswordAsHintError: 'Hint must be different from your password',
  Pause: 'Pause',
  'Payment.DemoNotice': 'This is a demo checkout. No real payment is processed.',
  'Payment.Expiry': 'Expiry',
  'Payment.Failed': 'Payment failed. Please try again.',
  'Payment.Processing': 'Processing…',
  'Payment.Title': 'Payment',
  PaymentCardNumber: 'Card Number',
  PaymentShippingEmailPlaceholder: 'Email',
  'Peer.Activity.Chat.Multi.RecordingAudio1': '%@ and %d others are recording voice',
  'Peer.Activity.Chat.Multi.RecordingVideo1': '%@ and %d others are recording video',
  'Peer.Activity.Chat.Multi.SendingFile1': '%@ and %d others are sending files',
  'Peer.Activity.Chat.Multi.SendingPhoto1': '%@ and %d others are sending photos',
  'Peer.Activity.Chat.Multi.SendingVideo1': '%@ and %d others are sending videos',
  'Peer.Activity.Chat.Multi.TypingText1': '%@ and %d others are typing',
  'Peer.Activity.Chat.Pair.RecordingAudio': '%1$@ and %2$@ are recording voice',
  'Peer.Activity.Chat.Pair.RecordingVideo': '%1$@ and %2$@ are recording video',
  'Peer.Activity.Chat.Pair.SendingFile': '%1$@ and %2$@ are sending files',
  'Peer.Activity.Chat.Pair.SendingPhoto': '%1$@ and %2$@ are sending photos',
  'Peer.Activity.Chat.Pair.SendingVideo': '%1$@ and %2$@ are sending videos',
  'Peer.Activity.Chat.Pair.TypingText': '%1$@ and %2$@ are typing',
  'Peer.Activity.Chat.RecordingAudio': '%@ is recording voice',
  'Peer.Activity.Chat.RecordingVideo': '%@ is recording video',
  'Peer.Activity.Chat.SendingFile': '%@ is sending a file',
  'Peer.Activity.Chat.SendingPhoto': '%@ is sending a photo',
  'Peer.Activity.Chat.SendingVideo': '%@ is sending a video',
  'Peer.Activity.Chat.TypingText': '%@ is typing',
  'Peer.Activity.User.RecordingAudio': 'recording voice',
  'Peer.Activity.User.RecordingVideo': 'recording video',
  'Peer.Activity.User.SendingFile': 'sending file',
  'Peer.Activity.User.SendingPhoto': 'sending a photo',
  'Peer.Activity.User.SendingVideo': 'sending a video',
  'Peer.Activity.User.TypingText': 'typing',
  'Peer.ServiceNotifications': 'service notifications',
  'Peer.Status.LastSeenAt': 'last seen %@ at %@',
  'Peer.Status.Today': 'today',
  'Peer.Status.Yesterday': 'yesterday',
  'Peer.Status.justNow': 'last seen just now',
  'Peer.Status.minAgo': {
    one_value: 'last seen %d minute ago',
    other_value: 'last seen %d minutes ago',
  },
  'Peer.Type.User': 'user',
  'PeerInfo.Action.VoiceChat': 'Video Chat',
  'PeerInfo.DeleteChannel': 'Delete Channel',
  'PeerInfo.DeleteContact': 'Delete Contact',
  'PeerInfo.Discussion': 'Discussion',
  'PeerInfo.SetAboutDescription': 'You can provide an optional description for your group.',
  'PeerInfo.Subscribers': 'Subscribers',
  'PeerMedia.Members': 'Members',
  PeopleCanJoinViaLinkCount: {
    one_value: '%s person can join via this link.',
    other_value: '%s people can join via this link.',
  },
  PeopleJoined: {
    one_value: '%1$d person joined',
    other_value: '%1$d people joined',
  },
  PeopleJoinedRemaining: {
    other_value: '%1$d remaining',
  },
  'Permissions.ExceptionsCount': { one_value: '%d exception', other_value: '%d exceptions' },
  'Permissions.NoExceptions': 'No exceptions',
  Phone: 'Phone',
  PhoneCopied: 'Phone copied to clipboard',
  'PhoneNumber.AlreadyTaken': 'This number is already connected to a Telegram account.',
  'PhoneNumber.Change': 'Change Number',
  'PhoneNumber.ChangeHint': 'Please confirm your country code and enter your new phone number.',
  PictureInPicture: 'Picture-in-Picture',
  PinAlsoFor: 'Also pin for %1$s',
  PinFolderLimitReached: 'Sorry, you can\'t pin any more chats to the top.',
  PinMessage: 'Pin',
  PinMessageAlert: 'Pin this message in the group?',
  PinMessageAlertChannel: 'Do you want to pin this message in this channel?',
  PinMessageAlertChat: 'Do you want to pin this message at the top of the chat?',
  PinMessageAlertTitle: 'Pin message',
  PinNotify: 'Notify all members',
  PinnedJoinCall: 'Join Call',
  PinnedMessage: 'Pinned Message',
  'PinnedMessage.Hide': 'Hide pinned message',
  'PinnedMessage.Show': 'Show pinned message',
  PinnedMessages: 'Pinned Messages',
  PinnedMessagesCount: { one_value: 'Pinned Message', other_value: '%1$d Pinned Messages' },
  'Pip.ActiveHint': 'To return to the tab, click the button here or the icon in the floating window.',
  'Pip.ActiveTitle': 'Telegram is open in Picture-in-Picture mode',
  'Pip.BackToTab': 'Back to Tab',
  Play: 'Play',
  PlaybackRateNormal: 'Normal',
  PleaseEnterCurrentPassword: 'Enter your password',
  PleaseEnterFirstPassword: 'Enter a password',
  PleaseReEnterPassword: 'Re-enter your password',
  PleaseWait: 'Please wait...',
  PmReadShowWhen: 'show when',
  Poll: 'Poll',
  PollOptions: 'Poll options',
  'Popup.Attach.AsMedia': 'Send as media',
  'Popup.Attach.EnableSpoilers': 'Hide all with spoilers',
  'Popup.Attach.RemoveSpoilers': 'Remove all spoilers',
  'Popup.Unpin.AllTitle': 'Unpin all messages',
  'Popup.Unpin.Hide': 'Hide',
  'Popup.Unpin.HideDescription': 'Do you want to hide the pinned message bar? It wil stay hidden until a new message is pinned.',
  'Popup.Unpin.HideTitle': 'Hide pinned messages',
  PostStatistics: 'Post Statistics',
  'PostsSearch.TabName': 'Posts',
  'Premium.Boarding.Avatar.Title': 'Animated Profile Pictures',
  'Premium.Boarding.Double.Title': 'Doubled Limits',
  'Premium.Boarding.NoAds.Title': 'No Ads',
  'Premium.Boarding.Stickers.Title': 'Premium Stickers',
  'Premium.Boarding.Title': 'Telegram Premium',
  'Premium.Boarding.Translate.Title': 'Real-Time Translation',
  'Premium.Feature.Avatar.Info': 'Upload a looping video as your profile picture.',
  'Premium.Feature.Badge.Info': 'Show a premium badge next to your name.',
  'Premium.Feature.Badge.Title': 'Premium Badge',
  'Premium.Feature.Chats.Info': 'Change default chat folder, archive and mute new chats.',
  'Premium.Feature.Chats.Title': 'Chat Management',
  'Premium.Feature.Double.Info': 'Up to 1000 channels, 20 folders, 10 pinned chats and 20 public links.',
  'Premium.Feature.Download.Info': 'Download media and files at the maximum speed.',
  'Premium.Feature.Download.Title': 'Faster Downloads',
  'Premium.Feature.Emoji.Info': 'Use unique animated emoji anywhere in chats.',
  'Premium.Feature.Emoji.Title': 'Custom Emoji',
  'Premium.Feature.FileSize.Info': 'Upload files of up to 4 GB each.',
  'Premium.Feature.FileSize.Title': 'Larger Uploads',
  'Premium.Feature.Intro': 'More freedom and dozens of exclusive features with a Telegram Premium subscription.',
  'Premium.Feature.NoAds.Info': 'Get rid of ads in public channels.',
  'Premium.Feature.Reactions.Info': 'React with a vastly expanded set of emoji.',
  'Premium.Feature.Reactions.Title': 'Unique Reactions',
  'Premium.Feature.Status.Info': 'Show a unique animated status next to your name.',
  'Premium.Feature.Status.Title': 'Emoji Status',
  'Premium.Feature.Stickers.Info': 'Unlock exclusive animated stickers.',
  'Premium.Feature.Stories.Info': 'Posting without limits, priority order, stealth mode, saved view history and more.',
  'Premium.Feature.Translate.Caption': 'Watch real-time chat translations with a Telegram Premium subscription.',
  'Premium.Feature.Translate.Info': 'Translate entire chats into your language.',
  'Premium.Feature.Voice.Info': 'Convert voice messages into text.',
  'Premium.Feature.Voice.Title': 'Voice-to-Text',
  'Premium.SubscribeFor': 'Subscribe for',
  'Premium.Tier.SixMonths': '6 Months',
  PremiumPreviewLastSeen: 'Last Seen Times',
  PremiumPreviewLastSeenDescription: 'View the last seen and read times of others even if you hide yours.',
  PremiumTierAnnual: 'Annual',
  PremiumTierMonthly: 'Monthly',
  'Presence.YourChat': 'chat with yourself',
  'PreviewSender.CaptionPlaceholder': 'Add a caption...',
  'PreviewSender.SendAlbum': {
    one_value: 'Send Album',
    other_value: 'Send %d Albums',
  },
  'PreviewSender.SendFile': {
    one_value: 'Send File',
    other_value: 'Send %d Files',
  },
  'PreviewSender.SendPhoto': {
    one_value: 'Send Photo',
    other_value: 'Send %d Photos',
  },
  'PreviewSender.SendVideo': {
    one_value: 'Send Video',
    other_value: 'Send %d Videos',
  },
  'Privacy.AlwaysShareCaption': 'These users will always see this, regardless of the setting above.',
  'Privacy.Bio': 'Who can see my bio',
  'Privacy.BioCaption': 'You can restrict who can see the bio on your profile with granular precision.',
  'Privacy.BioRow': 'Who can see my bio?',
  'Privacy.Birthday': 'Who can see my birthday',
  'Privacy.BirthdayCaption': 'You can restrict who can see your birthday with granular precision.',
  'Privacy.BirthdayRow': 'Who can see my birthday?',
  'Privacy.GroupsChoose': 'Choose who can add you to groups and channels.',
  'Privacy.MessagesCaption': 'Change who can send you messages.',
  'Privacy.MessagesCustomHelp': 'You can restrict who can send you messages with granular precision.',
  'Privacy.Passkey.Create': 'Create Passkey',
  'Privacy.Passkey.Created': 'Created %s',
  'Privacy.Passkey.LastUsage': 'used %s',
  'Privacy.Passkeys': 'Passkeys',
  'Privacy.Passkeys.Caption': 'Your passkey is stored securely in your password manager. [Learn more >]()',
  'Privacy.WhoCanSeeThis': 'Who can see this',
  'PrivacyAndSecurity.Item.Off': 'Off',
  'PrivacyAndSecurity.Item.On': 'On',
  PrivacyDeleteCloudDrafts: 'Delete All Cloud Drafts',
  PrivacyExceptions: 'Exceptions',
  PrivacyForwardsTitle: 'Who can add a link to my account when forwarding my messages?',
  PrivacyLastSeen: 'Last Seen & Online',
  PrivacyMessages: 'Messages',
  PrivacyMessagesTitle: 'Who can send me messages?',
  'PrivacyModal.Search.Placeholder': 'Add Users or Groups...',
  PrivacyPhone: 'Phone Number',
  PrivacyPhoneInfo: 'Users who have your number saved in their contacts will also see it on Telegram.',
  PrivacyPhoneInfo3: 'Users who add your number to their contacts will see it on Telegram only if they are your contacts.',
  PrivacyPhoneTitle: 'Who can see my phone number?',
  PrivacyPhoneTitle2: 'Who can find me by my number?',
  PrivacyProfilePhoto: 'Profile Photos',
  PrivacyProfilePhotoTitle: 'Who can see my profile photos?',
  PrivacySettings: 'Privacy and Security',
  'PrivacySettings.Forwards': 'Forwarded Messages',
  'PrivacySettings.Groups': 'Groups and Channels',
  'PrivacySettings.VoiceCalls': 'Calls',
  'PrivacySettingsController.AddUsers': 'Add Users',
  'PrivacySettingsController.AlwaysAllow': 'Always Allow',
  'PrivacySettingsController.AlwaysShare': 'Always Share With',
  'PrivacySettingsController.Everbody': 'Everybody',
  'PrivacySettingsController.Forwards.CustomHelp': 'You can restrict who can add a link to your account when forwarding your messages.',
  'PrivacySettingsController.GroupDescription': 'You can restrict who can add you to groups and channels with granular precision.',
  'PrivacySettingsController.LastSeenDescription': 'Unless you are a Premium user, you won\'t see Last Seen or Online statuses for people with whom you don\'t share yours. Approximate times will be shown instead (recently, within a week, within a month).',
  'PrivacySettingsController.MyContacts': 'My Contacts',
  'PrivacySettingsController.NeverAllow': 'Never Allow',
  'PrivacySettingsController.NeverShare': 'Never Share With',
  'PrivacySettingsController.Nobody': 'Nobody',
  'PrivacySettingsController.Paid': 'Paid',
  'PrivacySettingsController.PeerInfo': 'You can add users or entire groups as exceptions that will override the settings above.',
  'PrivacySettingsController.PhoneCallDescription': 'You can restrict who can call you with granular precision.',
  'PrivacySettingsController.ProfilePhoto.CustomHelp': 'You can restrict who can see your profile photo with granular precision.',
  'PrivacySettingsController.UserCount': {
    one_value: '%d user',
    other_value: '%d users',
  },
  PrivacyTitle: 'Privacy',
  PrivacyVoiceMessages: 'Voice Messages',
  PrivacyVoiceMessagesInfo: 'You can restrict who can send you voice or video messages with granular precision.',
  PrivacyVoiceMessagesTitle: 'Who can send me voice or video messages?',
  PrivateChat: 'Private Chat',
  'Profile.ChannelDescription': 'Channel description.',
  'Profile.Info.Channel': 'Channel Info',
  'Profile.Info.Group': 'Group Info',
  'Profile.Info.User': 'User Info',
  ProfileStories: 'Posts',
  'QRCode.Copied': 'QR Code copied to clipboard',
  'QRCode.CopiedLink': 'Profile link copied to clipboard',
  'QRCode.Copy': 'Copy QR Code',
  'QRCode.Title': 'QR Code',
  'QrLogin.Confirm.Action': 'Confirm',
  'QrLogin.Confirm.Text': 'Confirm the login on the new device',
  'QrLogin.Confirm.Title': 'Log in on a new device?',
  Reactions: 'Reactions',
  'Reactions.All.Info': 'Members of this group can use any emoji as reactions to messages.',
  'Reactions.None.Info': 'Members of this group cannot react to messages.',
  'Reactions.Some.Info': 'You can select emoji that will allow members of this group to react to messages.',
  Recent: 'Recent',
  RecentActions: 'Recent Actions',
  'RecentSessions.Error.FreshReset': 'For security reasons, you can\'t terminate older sessions from a device that you\'ve just connected. Please use an earlier connection or wait for a few hours.',
  RecoveryEmail: 'Recovery email',
  RecoveryEmailTitle: 'Recovery Email',
  Reminders: 'Reminders',
  Remove: 'Remove',
  RemovedUsers: 'Removed Users',
  'RemovedUsers.Description': 'Users removed by group admins cannot rejoin via invite links.',
  Reply: 'Reply',
  ReplyTo: 'Reply to %s',
  ReplyToAnotherChat: 'Reply in Another Chat',
  ReplyToQuote: 'Reply to quote by %s',
  'Report.DetailsPlaceholder': 'Additional details (optional)',
  'Report.Error': 'Could not send report',
  'Report.Sending': 'Sending…',
  'Report.Sent': 'Report sent',
  ReportBug: 'Report Bug',
  ReportChat: 'Report',
  ReportChatChild: 'Child Abuse',
  ReportChatPornography: 'Pornography',
  ReportChatSpam: 'Spam',
  ReportChatViolence: 'Violence',
  'RequestJoin.List.SearchEmpty': 'There were no results for "%@".\nTry a new search.',
  Resend: 'Resend',
  Reset: 'Reset',
  ResetAutomaticMediaDownload: 'Reset Auto-Download Settings',
  ResetAutomaticMediaDownloadAlert: 'Are you sure you want to reset auto-download settings?',
  ResetAutomaticMediaDownloadAlertTitle: 'Reset settings',
  RestartTopic: 'Reopen topic',
  RestrictedUsers: 'Restricted Users',
  'RestrictedUsers.Description': 'These members have limited rights in this group.',
  RevokeAlert: 'Are you sure you want to revoke this link? Once the link is revoked, no one will be able to join using it.',
  RevokeButton: 'Revoke',
  RevokeLink: 'Revoke Link',
  RevokedLinks: 'Revoked Links',
  'Rtmp.MediaViewer.Live': 'LIVE',
  'Rtmp.OutputPopup.Default': 'Default',
  'Rtmp.OutputPopup.Title': 'Output Device',
  'Rtmp.StreamPopup.Description': 'To stream video with another app, enter this Server URL and Stream Key in your streaming app. Software encoding recommended (x264 in OBS).',
  'Rtmp.StreamPopup.EndLiveStream': 'END LIVE STREAM',
  'Rtmp.StreamPopup.Hint': 'Once you start broadcasting in your streaming app, click Start Streaming below.',
  'Rtmp.StreamPopup.KeyCopied': 'Key copied to clipboard',
  'Rtmp.StreamPopup.RevokeStreamKey': 'Revoke Stream Key',
  'Rtmp.StreamPopup.ServerURL': 'Server URL',
  'Rtmp.StreamPopup.StartStreaming': 'START STREAMING',
  'Rtmp.StreamPopup.StreamKey': 'Stream Key',
  'Rtmp.StreamPopup.Title': 'Stream With...',
  'Rtmp.StreamPopup.TitleSettings': 'Stream Settings',
  'Rtmp.StreamPopup.URLCopied': 'URL copied to clipboard',
  'Rtmp.Topbar.Join': 'Join',
  'Rtmp.Topbar.NoViewers': 'No viewers',
  'Rtmp.Topbar.Title': 'Live Stream',
  'Rtmp.Watching': {
    other_value: '%s watching',
  },
  Save: 'Save',
  Saved: 'Saved',
  SavedGifsLimitTitle: 'Saved GIFs',
  SavedMessages: 'Saved Messages',
  'SavedTag.NamePlaceholder': 'Add a tag name',
  'SavedTag.Rename': 'Rename tag',
  'SavedTag.Tags': 'Tags',
  SavedTagFilterByTag: 'Filter by Tag',
  'Schedule.Repeat': 'Repeat',
  'Schedule.SendOn': 'Send on',
  'Schedule.SendTodayAt': 'Send today at',
  'Schedule.SendWhenOnline': 'Send When Online',
  'ScheduleController.at': 'at',
  ScheduledMessages: 'Scheduled Messages',
  Search: 'Search',
  'Search.Comments': 'Search comments',
  'Search.Confirm.ClearHistory': 'Are you sure you want to clear your search history?',
  'Search.Empty': 'There were no results for "**%@**". Try a new search.',
  'Search.EmptyFrom': 'There were no messages from **%@**.',
  'Search.EmptyHashtag': 'There were no results for "%@". Try another hashtag.',
  'Search.EmptyQuery': 'Try searching.',
  'Search.From': 'From:',
  'Search.Hashtag': 'Search Hashtag',
  'Search.HelpHashtag': 'Enter a hashtag to find messages containing it.',
  'Search.Member': 'Search Members',
  'Search.MyChannels': 'My Channels',
  SearchAllChatsShort: 'Chats',
  SearchAsChat: 'Show as Chat',
  SearchAsList: 'Show as List',
  SearchEmoji: 'Search Emoji',
  SearchEmptyViewTitle: 'No Results',
  SearchGIFs: 'Search GIFs',
  SearchGifsTitle: 'Search GIFs',
  SearchInAllChats: 'Search in All Chats',
  SearchMessages: 'Messages',
  Seconds: {
    one_value: '%1$d second',
    other_value: '%1$d seconds',
  },
  'SecretChat.Accept': 'Accept',
  'SecretChat.Awaiting': 'Waiting for the other party to accept the secret chat…',
  'SecretChat.EncryptionKey': 'Encryption Key',
  'SecretChat.Invitation': 'Secret chat invitation',
  'SecretChat.KeyNotReady': 'The encryption key has not been agreed yet.',
  'SecretChat.KeyVerification.Hint': 'Compare these emoji with the ones your contact sees on their device. If they match, the chat is end-to-end encrypted.',
  'SecretChat.New': 'New Secret Chat',
  'SecretChat.Reject': 'Decline',
  'SecretChat.Rejected': 'Secret chat rejected',
  Send: 'Send',
  SendAsFile: 'Send as file',
  SendMessage: 'Send Message',
  SendMessageTo: 'Add people...',
  'Separator.ShowLess': 'show less',
  'Separator.ShowMore': 'show more',
  SessionsInfo: 'Manage your sessions on all your devices.',
  SessionsListInfo: 'The official Telegram app is available for Android, iPhone, iPad, Windows, macOS and Linux.',
  SessionsTitle: 'Active Sessions',
  SetAsAdmin: 'Promote to admin',
  SetAsEmojiStatus: 'Set as Status',
  SetColor: 'Set a color',
  SetUrlPlaceholder: 'Link',
  Settings: 'Settings',
  'Settings.Limits': 'Limits',
  'Settings.Security': 'Security',
  Share: 'Share',
  ShareLink: 'Share Link',
  'ShareModal.Search.ForwardPlaceholder': 'Forward to...',
  ShareWith: 'Share with',
  SharedFilesTab2: 'Files',
  'SharedFolder.Cant.Share': 'you can\'t invite others here',
  'SharedFolder.Cant.ShareBots': 'you can\'t share chats with bots',
  'SharedFolder.Cant.ShareUsers': 'you can\'t share chats with users',
  'SharedFolder.CreateLink': 'Create a New Link',
  'SharedFolder.Description': 'Give your friends and colleagues access to the entire folder including all of its groups and channels where you have the necessary rights.',
  'SharedFolder.Edit.Description': 'Anyone with this link can add **%s** folder and the %s selected below',
  'SharedFolder.Edit.Subtitle': 'You can only share groups and channels in which you are allowed to create invite links.',
  'SharedFolder.Edit.Title': 'Share Folder',
  'SharedFolder.Includes': 'Includes %s',
  'SharedFolder.Link.Title': 'Add Folder',
  'SharedFolder.NoChats': 'There are no chats in this folder that you can share with others.',
  'SharedFolder.NoChats.Title': 'These chats cannot be shared',
  'SharedFolder.Toast.NeedName': 'Add a name for this folder to share it.',
  'SharedFolder.Toast.NoAdminChannel': 'You don\'t have the admin rights to share invite links to this channel.',
  'SharedFolder.Toast.NoAdminGroup': 'You don\'t have the admin rights to share invite links to this group chat.',
  'SharedFolder.Toast.NoExcluded': 'Excluded chats are not supported in shared folders.',
  'SharedFolder.Toast.NoPrivate': 'You can\'t share private chats.',
  'SharedFolder.Toast.NoTypes': 'Chat types are not supported in shared folders.',
  SharedLinksTab2: 'Links',
  'SharedMedia.Audio': 'Audio',
  'SharedMedia.Empty': 'Nothing here yet.',
  'SharedMedia.Gifts': 'Gifts',
  'SharedMedia.Gifts.Empty': 'No gifts yet',
  SharedMediaTab2: 'Media',
  SharedMusicTab2: 'Music',
  SharedVoiceTab2: 'Voice',
  ShowTranslateButton: 'Show Translate Button',
  ShowTranslateChatButton: 'Translate Entire Chats',
  'Sidebar.Resize.ShiftTip': 'Hold **Shift** to resize both columns at once',
  SimilarChannels: 'Similar Channels',
  Slowmode: 'Slow Mode',
  SlowmodeHours: '%1$dh',
  SlowmodeInfoOff: 'Choose how long each member must wait before sending their next message.',
  SlowmodeInfoSelected: 'Members will be able to send only one message every %1$s.',
  SlowmodeMinutes: '%1$dm',
  SlowmodeOff: 'Off',
  SlowmodeSeconds: '%1$ds',
  SomeReactions: 'Some reactions',
  'StarGift.ConvertTo': 'Convert to',
  'StarGift.GiftTo': 'Gift to',
  'StarGift.HiddenFromProfile': 'Hidden from your profile',
  'StarGift.HideFromProfile': 'Hide from Profile',
  'StarGift.MessagePlaceholder': 'Message (optional)',
  'StarGift.SendFor': 'Send for',
  'StarGift.Sent': 'Gift Sent',
  'StarGift.ShowInProfile': 'Show in Profile',
  'StarGift.ShowMyName': 'Show my name',
  'StarGift.View': 'View Gift',
  StarGiftCollectionsEmptyOther: 'No matching gifts.',
  StarGiftFromShort: 'From',
  StarGiftHideMyName: 'Hide My Name',
  StarGiftLimitedBadgeNum: '1 of %s',
  StarGiftSellTitleStars: 'Price in Stars',
  StarGiftShowLimited: 'Limited',
  StarGiftSoldOutBadge: 'sold out',
  StarGiftTitle: 'Gift',
  Stars: { one_value: '%d Star', other_value: '%d Stars' },
  'Stars.Balance': 'Your balance',
  'Stars.DemoNotice': 'Demo: top-up adds Stars instantly, no real payment.',
  'Stars.NotEnough': 'Not enough Stars — top up to continue.',
  'Stars.RecentTransactions': 'Recent Transactions',
  'Stars.Subscriptions.PerMonth': 'per month',
  'Stars.TopUpAction': 'Top up Stars',
  StarsFailed: 'Failed',
  'StarsRating.Back': 'Back',
  'StarsReaction.Caption': 'Choose how many Stars you want to send to support this message.',
  'StarsReaction.Title': 'React with Stars',
  StarsReactionTitle: 'Star Reaction',
  StarsReactionTopSenders: 'Top Senders',
  StarsTransactionsIncoming: 'Incoming',
  StarsTransactionsOutgoing: 'Outgoing',
  StartMessaging: 'Start Messaging',
  StatisticOverview: 'Overview',
  StatisticViews: 'Views',
  Statistics: 'Statistics',
  'Statistics.Forwards': 'Forwards',
  'Statistics.Loading': 'Loading statistics…',
  'Statistics.MediaPost': 'Media post',
  'Statistics.MemberGrowth': 'Member growth',
  'Statistics.Posts': 'Posts',
  'Statistics.PostsByDay': 'Posts by day',
  'Statistics.SubscriberGrowth': 'Subscriber growth',
  'Statistics.TopPosts': 'Top posts',
  'Statistics.TotalViews': 'Total views',
  'Statistics.Unavailable': 'Statistics are not available.',
  'Statistics.ViewsByDay': 'Views by day',
  Stickers: {
    one_value: '%1$d sticker',
    other_value: '%1$d stickers',
  },
  'Stickers.ClearRecent.Text': 'Are you sure you want to clear your recent stickers?',
  'Stickers.RemoveFromFavorites': 'Remove from Favorites',
  'Stickers.SearchAdd': 'Add',
  'Stickers.SearchAdded': 'Added',
  'Stickers.SuggestStickers': 'Suggest Stickers by Emoji',
  StickersBotInfo: 'Artists are welcome to add their own sticker sets using our @stickers bot.',
  StickersName: 'Stickers and Emoji',
  'StickersTab.SearchPlaceholder': 'Search Stickers',
  'StorageQuota.CacheSizeLimit': 'Cache size limit',
  'StorageQuota.CacheSizeLimitAuto': 'Auto',
  'StorageQuota.CachedFiles': 'Cached files',
  'StorageQuota.Caption': 'Note that cache required for the app to function properly will not be cleared.',
  'StorageQuota.Clear': 'Clear',
  'StorageQuota.ClearAll': 'Clear All',
  'StorageQuota.ClearAllConfirmation': 'Are you sure you want to clear all cached data?',
  'StorageQuota.ClearCacheOlderThan': 'Clear cache older than',
  'StorageQuota.ClearCachedFiles': 'Clear cached files',
  'StorageQuota.ClearConfirmation': 'Are you sure you want to clear %s of cached data?',
  'StorageQuota.ClearConfirmationUnknown': 'Are you sure you want to clear the cached data?',
  'StorageQuota.FailedToCalculate': 'Failed to calculate',
  'StorageQuota.Images': 'Images',
  'StorageQuota.Other': 'Other',
  'StorageQuota.StickersEmoji': 'Stickers and emojis',
  'StorageQuota.Title': 'Estimated storage quota',
  'StorageQuota.VideoFiles': 'Video files',
  Stories: 'Stories',
  'Stories.StealthMode.Activated.Title': 'Stealth Mode On',
  'Stories.StealthMode.Button': 'ENABLE STEALTH MODE',
  'Stories.StealthMode.Cooldown': 'Available in %s',
  'Stories.StealthMode.Cooldown.Title': 'Stealth Mode is on a cooldown',
  'Stories.StealthMode.Row1.Subtitle': 'Hide my views from the past **%s**.',
  'Stories.StealthMode.Row1.Title': 'Hide Recent Views',
  'Stories.StealthMode.Row2.Subtitle': 'Hide my views for the next **%s**.',
  'Stories.StealthMode.Row2.Title': 'Hide Upcoming Views',
  'Stories.StealthMode.Subtitle': 'Turn Stealth Mode on to watch without appearing in the list of viewers.',
  'Stories.StealthMode.Title': 'Stealth Mode',
  'Stories.StealthMode.Unavailable': 'Stealth Mode is unavailable',
  'Stories.StealthMode.View': 'Hide My View',
  'Story.AddToProfile': 'Post to Profile',
  'Story.Edit': 'Edit story',
  'Story.Edited': 'Story edited',
  'Story.React': 'React',
  'Story.RemoveFromProfile': 'Remove from Profile',
  'Story.Repost': 'Repost',
  'Story.Sound': 'Sound',
  'Story.Time.HoursAgo': 'h ago',
  'Story.Time.MinutesAgo': 'min ago',
  'Story.Viewers': 'Viewers',
  StoryJustNow: 'just now',
  StoryStatistics: 'Story Statistics',
  SubscribeRequests: 'Join Requests',
  Subscribers: {
    one_value: '%1$d subscriber',
    other_value: '%1$d subscribers',
  },
  SuggestBirthdayRow: 'Suggest Date of Birth',
  SuggestStickersAll: 'All Sets',
  SuggestStickersInstalled: 'My Sets',
  SuggestStickersNone: 'None',
  'SuggestedPosts.Empty': 'No suggested posts here yet…',
  'SuggestedPosts.PostPlaceholder': 'Type your post…',
  'SuggestedPosts.Publish': 'Publish',
  'SuggestedPosts.PublishingTime.Hint': 'Leave empty to publish anytime.',
  'SuggestedPosts.PublishingTime.Label': 'Publishing Time',
  'SuggestedPosts.Reject': 'Reject',
  'SuggestedPosts.Schedule': 'Schedule',
  'SuggestedPosts.Status.Approved': 'Approved',
  'SuggestedPosts.Status.OnReview': 'On review',
  'SuggestedPosts.Status.Rejected': 'Rejected',
  'SuggestedPosts.Submit': 'Suggest',
  'SuggestedPosts.SuggestAPost': 'Suggest a post',
  'SuggestedPosts.Title': 'Suggested Posts',
  'SuggestedPosts.YourPost': 'Your post',
  'SuggestedPosts.YourSuggestions': 'Your suggestions',
  'Suggestion.Notifications': 'Never miss a message! %s',
  'Suggestion.Notifications.Dismissed': 'You can turn notifications back on in the settings.',
  'Suggestion.Notifications.Subtitle': 'Enable notifications to stay updated.',
  'SupportStatus': 'support',
  'Telegram.GeneralSettingsViewController': 'General Settings',
  'Telegram.InstalledStickerPacksController': 'Stickers',
  'Telegram.LanguageViewController': 'Language',
  'Telegram.NotificationSettingsViewController': 'Notifications',
  TelegramFeatures: 'Telegram Features',
  TelegramFeaturesUrl: 'https://t.me/TelegramTips',
  TelegramStars: 'Telegram Stars',
  Terminate: 'Terminate',
  TerminateAllSessions: 'Terminate All Other Sessions',
  TerminateSessionText: 'Are you sure you want to terminate this session?',
  'Text.Context.Copy.Email': 'Copy Email',
  'Text.Context.Copy.Hashtag': 'Copy Hashtag',
  'Text.Context.Copy.Username': 'Copy Username',
  TextSize: 'Message Text Size',
  ThemeDay: 'Classic',
  ThemeLight: 'Day',
  ThemeNight: 'Night',
  ThemeTinted: 'Dark',
  TimeLimitHelp: 'You can make the link expire after a certain time.',
  TopicProfileStatus: 'In %s',
  Topics: 'Topics',
  TopicsCount: {
    one_value: '%d topic',
    other_value: '%d topics',
  },
  TranscribeHide: 'Hide Transcription',
  TranscribeUnavailable: 'Transcription unavailable in demo mode',
  TranscribeVoice: 'Transcribe Voice Message',
  Translate: 'Translate',
  'Translate.Failed': 'Translation failed',
  'Translate.FromLanguage': 'From language',
  'Translate.SectionCaption': 'Show a Translate button in the message menu to translate messages into your language.',
  'Translate.SectionTitle': 'Message Translation',
  'Translate.ToLanguage': 'To language',
  Translation: 'Translation',
  TurnPasswordOffQuestion: 'Are you sure you want to disable your password?',
  TurnPasswordOffQuestionTitle: 'Disable password',
  'TwoStepAuth.ChangeEmail': 'Change Recovery Email',
  'TwoStepAuth.ChangePassword': 'Change Password',
  'TwoStepAuth.ConfirmPassword': 'Please confirm your password.',
  'TwoStepAuth.CreateCaption': 'Create a password to protect your account.',
  'TwoStepAuth.GenericHelp': 'You have enabled Two-Step verification.\nYou\'ll need the password you set up here to log in to your Telegram account.',
  'TwoStepAuth.HintCaption': 'You can create an optional hint for your password.',
  'TwoStepAuth.ReEnterPassword': 'Re-enter Password',
  'TwoStepAuth.RecoveryEmailPlaceholder': 'Recovery email (optional)',
  'TwoStepAuth.RemovePassword': 'Disable Password',
  'TwoStepAuth.SetPasswordCaption': 'Set an additional password that will be required when you log in on a new device.',
  'TwoStepAuth.SetPasswordHelp': 'You can set a password that will be required when you log in on a new device in addition to the code you get in the SMS.',
  'TwoStepAuth.SetupEmail': 'Set Recovery Email',
  'TwoStepAuth.SetupHintPlaceholder': 'Hint',
  'TwoStepAuth.SetupHintTitle': 'Password Hint',
  TwoStepVerification: 'Two-Step Verification',
  TwoStepVerificationEmailSet: 'Recovery Email Set!',
  TwoStepVerificationEmailSetInfo: 'You will be able to use this recovery email to reset your password and restore access to your account.',
  TwoStepVerificationPasswordReturnSettings: 'Return to Settings',
  TwoStepVerificationPasswordSet: 'Password Set!',
  TwoStepVerificationPasswordSetInfo: 'This password will be required when you log in on a new device in addition to the code you get in the SMS.',
  TwoStepVerificationSetPassword: 'Set Password',
  TwoStepVerificationTitle: 'Two-Step Verification',
  TypePrivate: 'Private',
  TypePublic: 'Public',
  Unarchive: 'Unarchive',
  Unban: 'Unban',
  Unblock: 'Unblock',
  UnblockUser: 'Unblock user',
  'Unit.Bytes': 'B',
  'Unit.Days.Short': 'd',
  'Unit.Gigabytes': 'GB',
  'Unit.Hours.Short': 'h',
  'Unit.Kilobytes': 'KB',
  'Unit.Megabytes': 'MB',
  'Unit.Minutes.Short': 'm',
  'Unit.Months.Abbr': 'mo',
  'Unit.Seconds.Short': 's',
  UnpinMessage: 'Unpin',
  UnpinMessageAlertTitle: 'Unpin message',
  UnreadMessages: 'Unread Messages',
  UnsavedChanges: 'Unsaved Changes',
  UnsavedChangesDescription: 'Are you sure you want to discard all changes?',
  'UnsavedChangesDescription.Group': 'You have changed some settings in this group. Save changes?',
  'UnsavedChangesDescription.Privacy': 'You have changed some privacy settings. Save changes?',
  Update: 'UPDATE',
  Updating: 'Updating...',
  UserBio: 'Bio',
  UserBlocked: 'User blocked',
  'UserInfo.CustomPhotoHelp': 'Set a photo for this contact that only you will see, or suggest a new profile photo to them.',
  'UserInfo.PhotoResetToast': 'Custom photo removed',
  'UserInfo.PhotoSetToast': 'You will now always see this photo for %1$s\'s account.',
  'UserInfo.PhotoSuggestedToast': 'Photo suggested to %1$s',
  'UserInfo.RemovePersonalPhoto': 'Reset to Original Photo',
  'UserInfo.ResetCustomPhoto': 'Reset to Original Photo',
  'UserInfo.ResetCustomPhotoDescription': 'The custom photo for this contact will be removed and their profile photo will be shown instead.',
  'UserInfo.SetPhotoFor': 'Set Photo for %1$s',
  'UserInfo.SetPhotoTitle': 'Set Photo',
  'UserInfo.SuggestPhotoFor': 'Suggest Photo for %1$s',
  'UserInfo.UpdatePhotoFor': 'Change Photo for %1$s',
  'UserPermissions.Duration': 'Duration',
  'UserPermissions.Duration.Forever': 'Forever',
  'UserRestrictions.Action': 'Restrict',
  'UserRestrictions.CanDoMember': 'What can this member do?',
  'UserRestrictions.Title': 'Restrict Member',
  UserRestrictionsBlock: 'Ban and remove from group',
  UserRestrictionsBy: 'Restricted by %1$s',
  UserRestrictionsChangeInfo: 'Change Chat Info',
  UserRestrictionsDisabled: 'This option is disabled for all members in Group Permissions',
  UserRestrictionsInviteUsers: 'Add Users',
  UserRestrictionsNoChangeInfo: 'can\'t change Info',
  UserRestrictionsNoInviteUsers: 'can\'t add users',
  UserRestrictionsNoPinMessages: 'no pins',
  UserRestrictionsNoSend: 'can\'t send messages',
  UserRestrictionsNoSendMedia: 'no media',
  UserRestrictionsPinMessages: 'Pin Messages',
  UserRestrictionsSend: 'Send Messages',
  UserRestrictionsSendMedia: 'Send Media',
  UserRestrictionsSendRound: 'Send Video Messages',
  UserRestrictionsSendVoices: 'Send Voice Messages',
  UserUnblocked: 'User unblocked',
  Username: 'Username',
  UsernameCopied: 'Username copied to clipboard.',
  UsernameHelp: 'You can choose a username on **Telegram**. If you do, people will be able to find you by this username and contact you without needing your phone number.\n\nYou can use **a–z**, **0–9** and underscores. Minimum length is **5** characters.',
  Users: {
    one_value: '%1$d user',
    other_value: '%1$d users',
  },
  UsersOnly: 'Private Chats',
  UsesLimitHelp: 'You can make the link work only for a certain number of users.',
  'Verified.Bot': 'This bot is verified as official by the representatives of Telegram.',
  'Verified.Channel': 'This channel was verified by Telegram.',
  'Verified.Group': 'This group was verified by Telegram.',
  VideoCall: 'Video Call',
  ViewDiscussion: 'View discussion',
  ViewsPerPost: 'Views Per Post',
  'VoiceChat.Leave': 'Leave',
  'VoiceChat.Status.Listening': 'listening',
  'VoiceChat.Status.Members': {
    one_value: '%d participant',
    other_value: '%d participants',
  },
  'VoiceChat.Status.Muted': 'muted',
  'VoiceChat.Status.You': 'This is you',
  'VoiceChat.Topbar.Join': 'Join',
  VoipUnmute: 'Unmute',
  'WebApp.CameraDenied': 'Camera access denied',
  'WebApp.CloseConfirm': 'Close this Mini App?',
  'WebApp.DataSent': 'Data sent',
  'WebApp.PayConfirm': 'Pay this invoice?',
  'WebApp.PhoneRequest': 'Share your phone number with this bot?',
  'WebApp.QrUnsupported': 'QR scanning is not supported in this browser',
  'WebApp.WriteAccess.Question': 'Allow this bot to message you?',
  'WebPage.InstantView': 'INSTANT VIEW',
  Weeks: {
    one_value: '%1$d week',
    other_value: '%1$d weeks',
  },
  WhoCanAddMe: 'Who can add me?',
  WhoCanCallMe: 'Who can call me?',
  'WithinAMonth': 'last seen within a month',
  'WithinAWeek': 'last seen within a week',
  Years: {
    one_value: '%1$d year',
    other_value: '%1$d years',
  },
  Yesterday: 'yesterday',
  YourEmailSkip: 'Skip',
  YourEmailSkipWarning: 'Warning',
  YourEmailSkipWarningText: 'No, seriously.\n\nIf you forget your password, you will lose access to your Telegram account. There will be no way to restore it.',
  YourName: 'Your Name',
  messages: {
    one_value: '%1$d message',
    other_value: '%1$d messages',
  },
}

export default lang

/** Значение строки: обычная или с формами числа. */
export type LangPackValue = string | { one_value?: string; few_value?: string; many_value?: string; other_value?: string }

/** Символический ключ строки — как `keyof typeof lang` у tweb (`lib/langPack.ts:70`). */
export type LangPackKey = keyof typeof lang

